# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 05:35
from __future__ import unicode_literals

import ckeditor.fields
import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=128, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('body', ckeditor.fields.RichTextField()),
                ('status', models.CharField(choices=[(b'1', '\u041d\u0430 \u0440\u0430\u0441\u0441\u043c\u043e\u0442\u0440\u0435\u043d\u0438\u0438'), (b'2', '\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d\u043d\u0430\u044f'), (b'3', '\u041e\u0442\u043a\u043b\u043e\u043d\u0435\u043d\u043d\u0430\u044f')], max_length=1)),
            ],
            options={
                'verbose_name': '\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439 \u043a \u043d\u043e\u0432\u043e\u0441\u0442\u0438',
                'verbose_name_plural': '\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0438 \u043a \u043d\u043e\u0432\u043e\u0441\u0442\u044f\u043c',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('short', ckeditor.fields.RichTextField(blank=True, help_text='\u041a\u043e\u0440\u043e\u0442\u043a\u0430\u044f \u0432\u0435\u0440\u0441\u0438\u044f \u0442\u0435\u043a\u0441\u0442\u0430 \u043d\u043e\u0432\u043e\u0441\u0442\u0438/\u0441\u0442\u0430\u0442\u044c\u0438, \u0431\u0443\u0434\u0435\u0442 \u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c\u0441\u044f \u0432 \u043e\u0431\u0449\u0435\u043c \u0441\u043f\u0438\u043a\u0435 \u043d\u043e\u0432\u043e\u0441\u0442\u0435\u0439.', null=True, verbose_name='\u041a\u043e\u0440\u043e\u0442\u043a\u0430\u044f \u0432\u0435\u0440\u0441\u0438\u044f \u0442\u0435\u043a\u0441\u0442\u0430')),
                ('social_short', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u041a\u043e\u0440\u043e\u0442\u043a\u0438\u0439 \u0442\u0435\u043a\u0441\u0442 \u0434\u043b\u044f \u0441\u043e\u0446. \u0441\u0435\u0442\u0435\u0439')),
                ('body', ckeditor.fields.RichTextField(help_text='\u041f\u043e\u043b\u043d\u0430\u044f \u0432\u0435\u0440\u0441\u0438\u044f \u0442\u0435\u043a\u0441\u0442\u0430 \u043d\u043e\u0432\u043e\u0441\u0442\u0438/\u0441\u0442\u0430\u0442\u044c\u0438, \u0431\u0443\u0434\u0435\u0442 \u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c\u0441\u044f \u043f\u0440\u0438 \u0434\u0435\u0442\u0430\u043b\u044c\u043d\u043e\u043c \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u043d\u043e\u0432\u043e\u0441\u0442\u0438.', verbose_name='\u041f\u043e\u043b\u043d\u0430\u044f \u0432\u0435\u0440\u0441\u0438\u044f \u0442\u0435\u043a\u0441\u0442\u0430')),
                ('status', models.CharField(choices=[(b'1', '\u041d\u0430 \u0440\u0430\u0441\u0441\u043c\u043e\u0442\u0440\u0435\u043d\u0438\u0438'), (b'2', '\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d\u043d\u0430\u044f'), (b'3', '\u041e\u0442\u043a\u043b\u043e\u043d\u0435\u043d\u043d\u0430\u044f')], default=b'2', max_length=1, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('link', models.CharField(max_length=512)),
                ('color_code', models.CharField(max_length=8)),
                ('action', models.BooleanField(default=False, verbose_name='\u0410\u043a\u0446\u0438\u044f')),
                ('complete', models.BooleanField(default=False, verbose_name='\u0410\u043a\u0446\u0438\u044f \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0430?')),
                ('html_title', models.CharField(blank=True, default='', max_length=255, verbose_name='HTML Title')),
                ('original_image', imagekit.models.fields.ProcessedImageField(blank=True, default=True, upload_to=core.models.get_file_path, verbose_name='\u0444\u043e\u0442\u043e')),
                ('meta_description', models.CharField(blank=True, max_length=255, verbose_name=b'description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name=b'keywords')),
                ('seo_text', models.TextField(blank=True, verbose_name='SEO \u0442\u0435\u043a\u0441\u0442')),
                ('items', models.ManyToManyField(blank=True, to='catalog.Deckitem', verbose_name='\u0422\u043e\u0432\u0430\u0440 \u0432 \u0430\u043a\u0446\u0438\u0438')),
            ],
            options={
                'verbose_name': '\u041d\u043e\u0432\u043e\u0441\u0442\u044c/\u0421\u0442\u0430\u0442\u044c\u044f',
                'verbose_name_plural': '\u041d\u043e\u0432\u043e\u0441\u0442\u0438/\u0421\u0442\u0430\u0442\u044c\u0438',
            },
        ),
        migrations.CreateModel(
            name='Vopros_otvet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text=b'\xd0\xb8\xd1\x81\xd0\xbf\xd0\xbe\xd0\xbb\xd1\x8c\xd0\xb7\xd1\x83\xd0\xb5\xd1\x82\xd1\x81\xd1\x8f \xd0\xb4\xd0\xbb\xd1\x8f \xd1\x81\xd0\xbe\xd1\x80\xd1\x82\xd0\xb8\xd1\x80\xd0\xbe\xd0\xb2\xd0\xba\xd0\xb8', verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('vopros', models.CharField(max_length=512, verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441')),
                ('otvet', models.TextField(blank=True, null=True, verbose_name='\u041e\u0442\u0432\u0435\u0442')),
            ],
            options={
                'verbose_name': '\u0421\u043e\u0432\u0435\u0442 \u0432\u0435\u0442\u0435\u0440\u0438\u043d\u0430\u0440\u0430',
                'verbose_name_plural': '\u0421\u043e\u0432\u0435\u0442\u044b \u0432\u0435\u0442\u0435\u0440\u0438\u043d\u0430\u0440\u0430',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.New'),
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
