# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170124_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='color_code',
        ),
    ]
