# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-26 11:02
from __future__ import unicode_literals

import core.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_new_color_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': '\u041d\u043e\u0432\u043e\u0441\u0442\u044c/\u0410\u043a\u0446\u0438\u044f', 'verbose_name_plural': '\u041d\u043e\u0432\u043e\u0441\u0442\u0438/\u0410\u043a\u0446\u0438\u0438'},
        ),
        migrations.AlterField(
            model_name='new',
            name='original_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=core.models.get_file_path, verbose_name='\u0444\u043e\u0442\u043e'),
        ),
    ]
