# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-19 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_auto_20171119_1358'),
        ('news', '0005_auto_20170926_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Item', verbose_name=b'\xd0\xa2\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x80')),
            ],
            options={
                'verbose_name': '\u0442\u043e\u0432\u0430\u0440 \u0432 \u0430\u043a\u0446\u0438\u0438',
                'verbose_name_plural': '\u0442\u043e\u0432\u0430\u0440 \u0432 \u0430\u043a\u0446\u0438\u0438',
            },
        ),
        migrations.RemoveField(
            model_name='new',
            name='items',
        ),
        migrations.AddField(
            model_name='newitems',
            name='new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.New', verbose_name='\u0410\u043a\u0446\u0438\u044f'),
        ),
    ]
