# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-01-08 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20171119_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='discount_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440 \u0441\u043a\u0438\u0434\u043a\u0438'),
        ),
    ]
