# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-06-10 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200610_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a'),
        ),
    ]
