# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-06-10 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20200610_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ['-order'], 'verbose_name': '\u041d\u043e\u0432\u043e\u0441\u0442\u044c/\u0410\u043a\u0446\u0438\u044f', 'verbose_name_plural': '\u041d\u043e\u0432\u043e\u0441\u0442\u0438/\u0410\u043a\u0446\u0438\u0438'},
        ),
        migrations.AlterModelOptions(
            name='newitems',
            options={'ordering': ['order'], 'verbose_name': '\u0442\u043e\u0432\u0430\u0440 \u0432 \u0430\u043a\u0446\u0438\u0438', 'verbose_name_plural': '\u0442\u043e\u0432\u0430\u0440 \u0432 \u0430\u043a\u0446\u0438\u0438'},
        ),
        migrations.AddField(
            model_name='newitems',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a'),
        ),
    ]
