# Generated by Django 4.2.11 on 2024-03-25 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0108_alter_commentitem_status_alter_courier_name_and_more'),
        ('news', '0012_auto_20210608_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('1', 'На рассмотрении'), ('2', 'Опубликованная'), ('3', 'Отклоненная')], max_length=1),
        ),
        migrations.AlterField(
            model_name='new',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='new',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='new',
            name='status',
            field=models.CharField(choices=[('1', 'На рассмотрении'), ('2', 'Опубликованная'), ('3', 'Отклоненная')], default='2', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='newitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.item', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='vopros_otvet',
            name='date',
            field=models.DateTimeField(help_text='используется для сортировки', verbose_name='Дата публикации'),
        ),
    ]
