# Generated by Django 3.2.25 on 2024-05-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20240502_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='discount_size',
            field=models.FloatField(blank=True, null=True, verbose_name='Размер скидки'),
        ),
    ]
