# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 05:35
from __future__ import unicode_literals

import ckeditor.fields
import core.models
from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        # ('campaign', '0005_auto_20160216_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('source', models.IntegerField(blank=True, choices=[(1, '\u0417\u043d\u0430\u043a\u043e\u043c\u044b\u0439'), (2, '\u0412\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u0435'), (3, '\u041e\u0434\u043d\u043e\u043a\u043b\u0430\u0441\u0441\u043d\u0438\u043a\u0438'), (4, 'Facebook'), (5, 'Twitter'), (6, '\u0418\u043d\u0442\u0435\u0440\u043d\u0435\u0442'), (9, '\u0414\u0440\u0443\u0433\u043e\u0435')], default=9, null=True, verbose_name='\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a')),
                ('sale', models.FloatField(blank=True, choices=[(1, ' -- \u0431\u0435\u0437 \u0441\u043a\u0438\u0434\u043a\u0438 --'), (0.995, '\u041f\u043e\u0441\u0442\u043e\u044f\u043d\u043d\u044b\u0439 \u043f\u043e\u043a\u0443\u043f\u0430\u0442\u0435\u043b\u044c 0.5%'), (0.99, '\u041f\u043e\u0441\u0442\u043e\u044f\u043d\u043d\u044b\u0439 \u043f\u043e\u043a\u0443\u043f\u0430\u0442\u0435\u043b\u044c 1%'), (0.98, '\u041f\u043e\u0441\u0442\u043e\u044f\u043d\u043d\u044b\u0439 \u043f\u043e\u043a\u0443\u043f\u0430\u0442\u0435\u043b\u044c 2%'), (0.97, '\u041f\u043e\u0441\u0442\u043e\u044f\u043d\u043d\u044b\u0439 \u043f\u043e\u043a\u0443\u043f\u0430\u0442\u0435\u043b\u044c 3%'), (0.96, '\u041f\u043e\u0441\u0442\u043e\u044f\u043d\u043d\u044b\u0439 \u043f\u043e\u043a\u0443\u043f\u0430\u0442\u0435\u043b\u044c 4%'), (0.95, '\u041f\u043e\u0441\u0442\u043e\u044f\u043d\u043d\u044b\u0439 \u043f\u043e\u043a\u0443\u043f\u0430\u0442\u0435\u043b\u044c 5%'), (0.94, '\u041f\u043e\u0441\u0442\u043e\u044f\u043d\u043d\u044b\u0439 \u043f\u043e\u043a\u0443\u043f\u0430\u0442\u0435\u043b\u044c 6%'), (0.93, '\u041f\u043e\u0441\u0442\u043e\u044f\u043d\u043d\u044b\u0439 \u043f\u043e\u043a\u0443\u043f\u0430\u0442\u0435\u043b\u044c 7%'), (0.92, '\u041f\u043e\u0441\u0442\u043e\u044f\u043d\u043d\u044b\u0439 \u043f\u043e\u043a\u0443\u043f\u0430\u0442\u0435\u043b\u044c 8%'), (0.91, '\u041f\u043e\u0441\u0442\u043e\u044f\u043d\u043d\u044b\u0439 \u043f\u043e\u043a\u0443\u043f\u0430\u0442\u0435\u043b\u044c 9%'), (0.9, '\u041f\u043e\u0441\u0442\u043e\u044f\u043d\u043d\u044b\u0439 \u043f\u043e\u043a\u0443\u043f\u0430\u0442\u0435\u043b\u044c 10%'), (0.89, '\u041f\u043e\u0441\u0442\u043e\u044f\u043d\u043d\u044b\u0439 \u043f\u043e\u043a\u0443\u043f\u0430\u0442\u0435\u043b\u044c 11%'), (0.88, '\u041f\u043e\u0441\u0442\u043e\u044f\u043d\u043d\u044b\u0439 \u043f\u043e\u043a\u0443\u043f\u0430\u0442\u0435\u043b\u044c 12%'), (0.87, '\u041f\u043e\u0441\u0442\u043e\u044f\u043d\u043d\u044b\u0439 \u043f\u043e\u043a\u0443\u043f\u0430\u0442\u0435\u043b\u044c 13%'), (0.86, '\u041f\u043e\u0441\u0442\u043e\u044f\u043d\u043d\u044b\u0439 \u043f\u043e\u043a\u0443\u043f\u0430\u0442\u0435\u043b\u044c 14%'), (0.85, '\u041f\u043e\u0441\u0442\u043e\u044f\u043d\u043d\u044b\u0439 \u043f\u043e\u043a\u0443\u043f\u0430\u0442\u0435\u043b\u044c 15%'), (0.8, '\u041f\u043e\u0441\u0442\u043e\u044f\u043d\u043d\u044b\u0439 \u043f\u043e\u043a\u0443\u043f\u0430\u0442\u0435\u043b\u044c 20%'), (0.75, '\u041f\u043e\u0441\u0442\u043e\u044f\u043d\u043d\u044b\u0439 \u043f\u043e\u043a\u0443\u043f\u0430\u0442\u0435\u043b\u044c 25%')], help_text='\u0441\u043a\u0438\u0434\u043a\u0430 10% = 0.9', max_length=512, null=True, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('customer', models.BooleanField(default=False, verbose_name='\u041f\u043e\u043a\u0443\u043f\u0430\u0442\u0435\u043b\u044c')),
                ('repeat_customer', models.BooleanField(default=False, verbose_name='\u041f\u043e\u0432\u0442\u043e\u0440\u043d\u044b\u0439 \u043f\u043e\u043a\u0443\u043f\u0430\u0442\u0435\u043b\u044c')),
                ('free_shipping', models.BooleanField(default=False, verbose_name='\u0411\u0435\u0441\u043f\u043b\u0430\u0442\u043d\u0430\u044f \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0430')),
                ('free_buyer', models.BooleanField(default=False, verbose_name='\u041f\u043e\u043a\u0443\u043f\u0430\u0442\u044c \u043f\u043e \u0441\u0435\u0431\u0435\u0441\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u0438')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=128, unique=True, verbose_name='\u0423\u043d\u0438\u043a\u0430\u043b\u044c\u043d\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0448\u0430\u0431\u043b\u043e\u043d\u0430')),
                ('title', models.CharField(max_length=128, verbose_name='\u0422\u0435\u043a\u0441\u0442\u043e\u0432\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0434\u043b\u044f \u0430\u0434\u043c\u0438\u043d\u043a\u0438')),
                ('subject', models.CharField(max_length=256, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u0438\u0441\u044c\u043c\u0430')),
                ('body', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u0438\u0441\u044c\u043c\u0430')),
                ('type', models.IntegerField(choices=[(1, '\u041a\u043b\u0438\u0435\u043d\u0442\u0441\u043a\u043e\u0435'), (2, '\u0412\u043d\u0443\u0442\u0440\u0435\u043d\u043d\u0435\u0435')], verbose_name='\u0442\u0438\u043f')),
            ],
            options={
                'verbose_name': '\u0422\u0435\u043a\u0441\u0442 \u043f\u0438\u0441\u044c\u043c\u0430',
                'verbose_name_plural': '\u0422\u0435\u043a\u0441\u0442\u044b \u043f\u0438\u0441\u0435\u043c',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=512, null=True, verbose_name='\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('extra_class', models.CharField(blank=True, max_length=512, null=True, verbose_name='\u041a\u043b\u0430\u0441\u0441\u044b')),
                ('position', models.IntegerField(default=99, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a')),
                ('menu_type', models.IntegerField(choices=[(0, '\u041c\u0435\u043d\u044e \u043d\u0430 \u0433\u043b\u0430\u0432\u043d\u043e\u0439'), (1, '\u041b\u0435\u0432\u043e\u0435 \u043c\u0435\u043d\u044e'), (2, '\u043d\u0435 \u043e\u043f\u0440\u0435\u0434\u0435\u043b\u0435\u043d\u043e')])),
                ('icon', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=core.models.get_file_path, verbose_name='\u0438\u043a\u043e\u043d\u043a\u0430')),
                ('link', models.CharField(blank=True, max_length=512, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
            ],
            options={
                'ordering': ['menu_type', 'position'],
                'verbose_name': '\u041c\u0435\u043d\u044e',
                'verbose_name_plural': '\u041c\u0435\u043d\u044e',
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send', models.BooleanField(default=True)),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Mail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('extra_class', models.CharField(blank=True, max_length=512, null=True, verbose_name='\u041a\u043b\u0430\u0441\u0441\u044b')),
                ('position', models.IntegerField(default=99, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('short', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='\u041a\u043e\u0440\u043e\u0442\u043a\u0430\u044f \u0432\u0435\u0440\u0441\u0438\u044f')),
                ('body', ckeditor.fields.RichTextField(verbose_name='\u0421\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u0435')),
                ('background', imagekit.models.fields.ProcessedImageField(upload_to=core.models.get_file_path, verbose_name='\u0444\u043e\u043d')),
                ('section', models.CharField(choices=[('dlya-sobak', '\u0414\u043b\u044f \u0441\u043e\u0431\u0430\u043a'), ('dlya-koshek', '\u0414\u043b\u044f \u043a\u043e\u0448\u0435\u043a'), ('dlya-gryzunov-i-harkov', '\u0414\u043b\u044f \u0433\u0440\u044b\u0437\u0443\u043d\u043e\u0432 \u0438 \u0445\u043e\u0440\u044c\u043a\u043e\u0432'), ('dlya-ptiz', '\u0414\u043b\u044f \u043f\u0442\u0438\u0446'), ('dlya-rybok', '\u0414\u043b\u044f \u0440\u044b\u0431\u043e\u043a'), ('dlya-reptiliy', '\u0414\u043b\u044f \u0440\u0435\u043f\u0442\u0438\u043b\u0438\u0439')], max_length=128, verbose_name='\u0420\u0430\u0437\u0434\u0435\u043b')),
                ('link', models.CharField(blank=True, max_length=512, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
            ],
            options={
                'ordering': ['position'],
                'verbose_name': '\u0421\u0442\u0430\u0442\u044c\u044f',
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u044c\u0438',
            },
        ),
        migrations.CreateModel(
            name='Parametr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('original_image', imagekit.models.fields.ProcessedImageField(upload_to=core.models.get_file_path, verbose_name='\u0444\u043e\u0442\u043e')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': '\u0424\u043e\u0442\u043e \u0444\u0430\u0439\u043b',
                'verbose_name_plural': '\u0424\u043e\u0442\u043e \u0444\u0430\u0439\u043b\u044b',
            },
        ),
        migrations.CreateModel(
            name='Restore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdate', models.DateTimeField(auto_now_add=True)),
                ('hash', models.CharField(max_length=255)),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u0417\u0430\u0431\u044b\u0442\u044b\u0435 \u043f\u0430\u0440\u043e\u043b\u0438',
                'verbose_name_plural': '\u0417\u0430\u0431\u044b\u0442\u044b\u0435 \u043f\u0430\u0440\u043e\u043b\u0438',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=512, null=True)),
                ('date', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('body', models.TextField(help_text='\u041f\u043e\u043b\u043d\u0430\u044f \u0432\u0435\u0440\u0441\u0438\u044f \u0442\u0435\u043a\u0441\u0442\u0430 \u043d\u043e\u0432\u043e\u0441\u0442\u0438, \u0431\u0443\u0434\u0435\u0442 \u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c\u0441\u044f \u043f\u0440\u0438 \u0434\u0435\u0442\u0430\u043b\u044c\u043d\u043e\u043c \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u043d\u043e\u0432\u043e\u0441\u0442\u0438.', verbose_name='\u041f\u043e\u043b\u043d\u0430\u044f \u0432\u0435\u0440\u0441\u0438\u044f \u0442\u0435\u043a\u0441\u0442\u0430')),
                ('status', models.CharField(choices=[(b'1', '\u041e\u0436\u0438\u0434\u0430\u0435\u0442 \u043c\u043e\u0434\u0435\u0440\u0430\u0446\u0438\u0438'), (b'2', '\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d\u043d\u044b\u0439'), (b'3', '\u041e\u0442\u043a\u043b\u044e\u0447\u0435\u043d\u043d\u0430\u044f')], default=b'2', max_length=1, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('color_code', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': '\u041e\u0442\u0437\u044b\u0432',
                'verbose_name_plural': '\u041e\u0442\u0437\u044b\u0432\u044b',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='\u0432\u044b\u0432\u043e\u0434\u0438\u0442\u0441\u044f \u0442\u043e\u043b\u044c\u043a\u043e \u0432 \u0430\u0434\u043c\u0438\u043d\u043a\u0435', max_length=256, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('slide_title', models.CharField(blank=True, max_length=512, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('slide_title_link', models.CharField(blank=True, max_length=512, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043a\u0430')),
                ('slide_description', models.CharField(blank=True, max_length=512, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('slide_description_link', models.CharField(blank=True, max_length=512, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u0441 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u044f')),
                ('slide_link', models.CharField(blank=True, max_length=512, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0432\u0441\u0435\u043c \u0441\u043b\u0430\u0439\u0434\u0435')),
                ('slide_image', imagekit.models.fields.ProcessedImageField(upload_to=core.models.get_file_path, verbose_name='\u0444\u043e\u043d')),
                ('startdate', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u0437\u0430\u043f\u0443\u0441\u043a\u0430')),
                ('expdate', models.DateField(verbose_name='\u0413\u043e\u0434\u0435\u043d \u0434\u043e')),
                ('position', models.IntegerField(default=9, verbose_name='\u041f\u043e\u0437\u0438\u0446\u0438\u044f')),
            ],
            options={
                'ordering': ['position'],
                'verbose_name': '\u0421\u043b\u0430\u0439\u0434-\u0431\u0430\u043d\u043d\u0435\u0440',
                'verbose_name_plural': '\u0421\u043b\u0430\u0439\u0434-\u0431\u0430\u043d\u043d\u0435\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='Static',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('body', ckeditor.fields.RichTextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b')),
                ('link', models.CharField(blank=True, help_text='\u042d\u0442\u043e \u043f\u043e\u043b\u0435 \u0437\u0430\u043f\u043e\u043b\u043d\u044f\u0435\u0442\u0441\u044f \u041e\u043f\u0442\u0438\u043c\u0438\u0437\u0430\u0442\u043e\u0440\u043e\u043c \u0441\u0430\u0439\u0442\u0430, \u0438 \u043c\u043e\u0436\u0435\u0442 \u0431\u044b\u0442\u044c \u043e\u0441\u0442\u0430\u0432\u043b\u0435\u043d\u043e \u043f\u0443\u0441\u0442\u044b\u043c.', max_length=512, null=True, verbose_name='URL \u0430\u0434\u0440\u0435\u0441 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b')),
                ('menu', models.CharField(choices=[(b'1', '\u041d\u0435\u0442 \u0432 \u043c\u0435\u043d\u044e'), (b'2', '\u0420\u0430\u0437\u0434\u0435\u043b \u043e\u0441\u043d\u043e\u0432\u043d\u043e\u0433\u043e \u043c\u0435\u043d\u044e'), (b'3', '\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0435 \u043c\u0435\u043d\u044e \u21161'), (b'4', '\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0435 \u043c\u0435\u043d\u044e \u21162'), (b'5', '\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0435 \u043c\u0435\u043d\u044e \u21163')], default=1, max_length=1, verbose_name='\u0420\u0430\u0441\u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435 \u0440\u0430\u0437\u0434\u0435\u043b\u0430')),
                ('active', models.BooleanField(default=1, verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430')),
                ('number', models.IntegerField(default=19, help_text='\u041f\u0435\u0440\u0432\u044b\u043c \u0432 \u043c\u0435\u043d\u044e \u0431\u0443\u0434\u0435\u0442 \u0442\u043e\u0442 \u0440\u0430\u0437\u0434\u0435\u043b, \u0447\u0435\u0439 \u043d\u043e\u043c\u0435\u0440 \u043c\u0435\u043d\u044c\u0448\u0435.', verbose_name='\u041f\u043e\u0437\u0438\u0446\u0438\u044f \u0432 \u043c\u0435\u043d\u044e')),
                ('meta_title', models.CharField(blank=True, help_text='\u042d\u0442\u043e \u043f\u043e\u043b\u0435 \u0437\u0430\u043f\u043e\u043b\u043d\u044f\u0435\u0442\u0441\u044f \u041e\u043f\u0442\u0438\u043c\u0438\u0437\u0430\u0442\u043e\u0440\u043e\u043c \u0441\u0430\u0439\u0442\u0430, \u0438 \u043c\u043e\u0436\u0435\u0442 \u0431\u044b\u0442\u044c \u043e\u0441\u0442\u0430\u0432\u043b\u0435\u043d\u043e \u043f\u0443\u0441\u0442\u044b\u043c.', max_length=1024, null=True, verbose_name='\u041c\u0435\u0442\u0430 title')),
                ('meta_descroption', models.CharField(blank=True, help_text='\u042d\u0442\u043e \u043f\u043e\u043b\u0435 \u0437\u0430\u043f\u043e\u043b\u043d\u044f\u0435\u0442\u0441\u044f \u041e\u043f\u0442\u0438\u043c\u0438\u0437\u0430\u0442\u043e\u0440\u043e\u043c \u0441\u0430\u0439\u0442\u0430, \u0438 \u043c\u043e\u0436\u0435\u0442 \u0431\u044b\u0442\u044c \u043e\u0441\u0442\u0430\u0432\u043b\u0435\u043d\u043e \u043f\u0443\u0441\u0442\u044b\u043c.', max_length=1024, null=True, verbose_name='\u041c\u0435\u0442\u0430 descroption')),
                ('meta_keywords', models.CharField(blank=True, help_text='\u042d\u0442\u043e \u043f\u043e\u043b\u0435 \u0437\u0430\u043f\u043e\u043b\u043d\u044f\u0435\u0442\u0441\u044f \u041e\u043f\u0442\u0438\u043c\u0438\u0437\u0430\u0442\u043e\u0440\u043e\u043c \u0441\u0430\u0439\u0442\u0430, \u0438 \u043c\u043e\u0436\u0435\u0442 \u0431\u044b\u0442\u044c \u043e\u0441\u0442\u0430\u0432\u043b\u0435\u043d\u043e \u043f\u0443\u0441\u0442\u044b\u043c.', max_length=1024, null=True, verbose_name='\u041c\u0435\u0442\u0430 keywords')),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438\u0439 \u0440\u0430\u0437\u0434\u0435\u043b',
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438\u0435 \u0440\u0430\u0437\u0434\u0435\u043b\u044b',
            },
        ),
        # migrations.CreateModel(
        #     name='SubscriberListSettings',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('visible', models.BooleanField(default=False, verbose_name='\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u0432 \u043d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0430\u0445 \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0438 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f?')),
        #         ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u0443\u043d\u043a\u0442\u0430 \u0432 \u043d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0430\u0445 \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0438')),
        #         ('subscriberlist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campaign.SubscriberList', verbose_name='\u0421\u043f\u0438\u0441\u043e\u043a \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0438')),
        #     ],
        #     options={
        #         'verbose_name': '\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u0441\u043f\u0438\u0441\u043a\u0430 \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0438',
        #         'verbose_name_plural': '\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u0441\u043f\u0438\u0441\u043a\u043e\u0432 \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0438',
        #     },
        # ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='\u0422\u043e\u043a\u0435\u043d')),
                ('dateend', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u044f \u0434\u0435\u0439\u0441\u0442\u0432\u0438\u044f')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041a\u043e\u043c\u0443')),
            ],
        ),
        # migrations.CreateModel(
        #     name='Unsubscribed',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('subscriberlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.SubscriberList')),
        #         ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unsubscribe_items', to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),
        # migrations.AddField(
        #     model_name='account',
        #     name='unsubscribed',
        #     field=models.ManyToManyField(through='core.Unsubscribed', to='campaign.SubscriberList', verbose_name='\u041e\u0442\u043f\u0438\u0441\u0430\u043b\u0441\u044f \u043e\u0442'),
        # ),
        migrations.AddField(
            model_name='account',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationsettings',
            unique_together=set([('user', 'mail')]),
        ),
    ]
