# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 13:48
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='slide_image',
            field=models.ImageField(upload_to=core.models.get_file_path, verbose_name='\u0444\u043e\u043d'),
        ),
    ]
