# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160303_1348'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='unsubscribed',
        #     name='subscriberlist',
        # ),
        # migrations.RemoveField(
        #     model_name='unsubscribed',
        #     name='user',
        # ),
        # migrations.RemoveField(
        #     model_name='account',
        #     name='unsubscribed',
        # ),
        # migrations.AddField(
        #     model_name='account',
        #     name='unsubscribed',
        #     field=models.BooleanField(default=False, verbose_name='\u041e\u0442\u043f\u0438\u0441\u0430\u043d \u043e\u0442 \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0438'),
        # ),
        # migrations.DeleteModel(
        #     name='Unsubscribed',
        # ),
    ]
