# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160322_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a \u0443\u0437\u043d\u0430\u0432\u0430\u043d\u0438\u044f',
                'verbose_name_plural': '\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a\u0438 \u0443\u0437\u043d\u0430\u0432\u0430\u043d\u0438\u044f',
            },
        ),
        migrations.RemoveField(
            model_name='account',
            name='source',
        ),
        migrations.AddField(
            model_name='account',
            name='usersource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.UserSource'),
        ),
    ]
