# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 15:44
from __future__ import unicode_literals

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160424_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, '\u0422\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044f \u0437\u0432\u043e\u043d\u043e\u043a'), (2, '\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e \u043f\u0435\u0440\u0435\u0437\u0432\u043e\u043d\u0438\u0442\u044c'), (3, '\u041d\u0435 \u0443\u0434\u0430\u043b\u043e\u0441\u044c \u0434\u043e\u0437\u0432\u043e\u043d\u0438\u0442\u044c\u0441\u044f'), (4, ''), (5, ''), (6, ''), (7, ''), (11, '\u041e\u0444\u043e\u0440\u043c\u0438\u043b/\u043e\u0444\u043e\u0440\u043c\u0438\u0442 \u0437\u0430\u043a\u0430\u0437'), (12, '\u0423\u0448\u0435\u043b \u043a \u043a\u043e\u043d\u043a\u0443\u0440\u0435\u043d\u0442\u0430\u043c'), (13, '\u041f\u0438\u0442\u043e\u043c\u0446\u0430 \u0431\u043e\u043b\u044c\u0448\u0435 \u043d\u0435\u0442'), (14, '\u041f\u0435\u0440\u0435\u0448\u0435\u043b \u043d\u0430 \u043a\u043e\u0440\u043c, \u043a\u043e\u0442\u043e\u0440\u043e\u0433\u043e \u0443 \u043d\u0430\u0441 \u043d\u0435\u0442')], default=0, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('description', models.TextField(blank=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u0442\u0435\u0440\u044f\u043d\u043d\u044b\u0435 \u043f\u043e\u043a\u0443\u043f\u0430\u0442\u0435\u043b\u0438',
                'verbose_name_plural': '\u041f\u043e\u0442\u0435\u0440\u044f\u043d\u043d\u044b\u0435 \u043f\u043e\u043a\u0443\u043f\u0430\u0442\u0435\u043b\u0438',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='slide_image',
            field=models.ImageField(default=0, upload_to=core.models.get_file_path, verbose_name='\u0444\u043e\u043d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='usersource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.UserSource', verbose_name='\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a'),
        ),
        migrations.AddField(
            model_name='lostuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043a\u0443\u043f\u0430\u0442\u0435\u043b\u044c'),
        ),
    ]
