# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 10:52
from __future__ import unicode_literals

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160514_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostuser',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 26, 10, 52, 49, 886608), verbose_name='\u0414\u0430\u0442\u0430 \u0437\u0430\u043d\u0435\u0441\u0435\u043d\u0438\u044f'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lostuser',
            name='status',
            field=models.IntegerField(choices=[(1, '\u0422\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044f \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0430'), (2, '\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e \u043f\u0435\u0440\u0435\u0437\u0432\u043e\u043d\u0438\u0442\u044c'), (3, '\u041d\u0435 \u0443\u0434\u0430\u043b\u043e\u0441\u044c \u0434\u043e\u0437\u0432\u043e\u043d\u0438\u0442\u044c\u0441\u044f'), (4, ''), (5, ''), (6, ''), (7, ''), (11, '\u041e\u0444\u043e\u0440\u043c\u0438\u043b/\u043e\u0444\u043e\u0440\u043c\u0438\u0442 \u0437\u0430\u043a\u0430\u0437'), (12, '\u0423\u0448\u0435\u043b \u043a \u043a\u043e\u043d\u043a\u0443\u0440\u0435\u043d\u0442\u0430\u043c'), (13, '\u041f\u0438\u0442\u043e\u043c\u0446\u0430 \u0431\u043e\u043b\u044c\u0448\u0435 \u043d\u0435\u0442'), (14, '\u041f\u0435\u0440\u0435\u0448\u0435\u043b \u043d\u0430 \u043a\u043e\u0440\u043c, \u043a\u043e\u0442\u043e\u0440\u043e\u0433\u043e \u0443 \u043d\u0430\u0441 \u043d\u0435\u0442')], default=0, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slide_image',
            field=models.ImageField(blank=True, upload_to=core.models.get_file_path, verbose_name='\u0432 \u0441\u043b\u0430\u0439\u0434\u0435\u0440'),
        ),
    ]
