# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-27 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160526_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostuser',
            name='average',
            field=models.PositiveIntegerField(default=0, verbose_name='\u0421\u0440\u0435\u0434\u043d\u0435\u0435'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lostuser',
            name='last_order',
            field=models.PositiveIntegerField(default=0, verbose_name='\u041f\u043e\u0441\u043b\u0435\u0434\u043d\u0438\u0439 \u0437\u0430\u043a\u0430\u0437'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lostuser',
            name='mediana',
            field=models.PositiveIntegerField(default=0, verbose_name='\u041c\u0435\u0434\u0438\u0430\u043d\u0430'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lostuser',
            name='need_again',
            field=models.BooleanField(default=False, verbose_name='\u041e\u0431\u0440\u0430\u0431\u043e\u0442\u0430\u0442\u044c \u043f\u043e\u0432\u0442\u043e\u0440\u043d\u043e'),
        ),
        migrations.AddField(
            model_name='lostuser',
            name='order_count',
            field=models.PositiveIntegerField(default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0437\u0430\u043a\u0430\u0437\u043e\u0432'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lostuser',
            name='status',
            field=models.IntegerField(choices=[(1, '\u0422\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044f \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0430'), (2, '\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e \u043f\u0435\u0440\u0435\u0437\u0432\u043e\u043d\u0438\u0442\u044c'), (3, '\u041d\u0435 \u0443\u0434\u0430\u043b\u043e\u0441\u044c \u0434\u043e\u0437\u0432\u043e\u043d\u0438\u0442\u044c\u0441\u044f'), (4, '\u041d\u0435 \u0442\u0440\u043e\u0433\u0430\u0439 \u043c\u0435\u043d\u044f'), (5, ''), (6, ''), (7, ''), (11, '\u041e\u0444\u043e\u0440\u043c\u0438\u043b/\u043e\u0444\u043e\u0440\u043c\u0438\u0442 \u0437\u0430\u043a\u0430\u0437'), (12, '\u0423\u0448\u0435\u043b \u043a \u043a\u043e\u043d\u043a\u0443\u0440\u0435\u043d\u0442\u0430\u043c'), (13, '\u041f\u0438\u0442\u043e\u043c\u0446\u0430 \u0431\u043e\u043b\u044c\u0448\u0435 \u043d\u0435\u0442'), (14, '\u041f\u0435\u0440\u0435\u0448\u0435\u043b \u043d\u0430 \u043a\u043e\u0440\u043c, \u043a\u043e\u0442\u043e\u0440\u043e\u0433\u043e \u0443 \u043d\u0430\u0441 \u043d\u0435\u0442'), (15, '\u0412\u044b\u0441\u043e\u043a\u0430\u044f \u0446\u0435\u043d\u0430, \u043f\u043e\u043c\u043e\u0447\u044c \u043d\u0435 \u043c\u043e\u0436\u0435\u043c')], default=0, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441'),
        ),
    ]
