# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 16:32
from __future__ import unicode_literals

import ckeditor.fields
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160527_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('short', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='\u0442\u0435\u043a\u0441\u0442')),
                ('link', models.CharField(blank=True, max_length=512, null=True, verbose_name='\u0441\u0441\u044b\u043b\u043a\u0430')),
                ('screnshot', models.ImageField(blank=True, upload_to=core.models.get_file_path, verbose_name='\u0432 \u0441\u043b\u0430\u0439\u0434\u0435\u0440')),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': '\u041e\u0442\u0437\u044b\u0432',
                'verbose_name_plural': '\u041e\u0442\u0437\u044b\u0432\u044b',
            },
        ),
        migrations.AlterField(
            model_name='lostuser',
            name='status',
            field=models.IntegerField(choices=[(1, '\u0422\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044f \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0430'), (2, '\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e \u043f\u0435\u0440\u0435\u0437\u0432\u043e\u043d\u0438\u0442\u044c'), (3, '\u041d\u0435 \u0443\u0434\u0430\u043b\u043e\u0441\u044c \u0434\u043e\u0437\u0432\u043e\u043d\u0438\u0442\u044c\u0441\u044f'), (4, '\u041d\u0435 \u0442\u0440\u043e\u0433\u0430\u0439 \u043c\u0435\u043d\u044f'), (5, ''), (6, ''), (7, ''), (11, '\u041e\u0444\u043e\u0440\u043c\u0438\u043b/\u043e\u0444\u043e\u0440\u043c\u0438\u0442 \u0437\u0430\u043a\u0430\u0437'), (12, '\u0423\u0448\u0435\u043b \u043a \u043a\u043e\u043d\u043a\u0443\u0440\u0435\u043d\u0442\u0430\u043c'), (13, '\u041f\u0438\u0442\u043e\u043c\u0446\u0430 \u0431\u043e\u043b\u044c\u0448\u0435 \u043d\u0435\u0442'), (14, '\u041f\u0435\u0440\u0435\u0448\u0435\u043b \u043d\u0430 \u043a\u043e\u0440\u043c, \u043a\u043e\u0442\u043e\u0440\u043e\u0433\u043e \u0443 \u043d\u0430\u0441 \u043d\u0435\u0442'), (15, '\u0412\u044b\u0441\u043e\u043a\u0430\u044f \u0446\u0435\u043d\u0430, \u043f\u043e\u043c\u043e\u0447\u044c \u043d\u0435 \u043c\u043e\u0436\u0435\u043c')], default=1, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441'),
        ),
    ]
