# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-11 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20160615_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialreview',
            name='date',
            field=models.DateTimeField(verbose_name='\u0434\u0430\u0442\u0430'),
        ),
    ]
