# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-24 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20161213_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='show_on_top',
            field=models.BooleanField(default=False, verbose_name='\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u0441\u0432\u0435\u0440\u0445\u0443'),
        ),
    ]
