# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-28 17:28
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_menu_show_on_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0438'),
        ),
    ]
