# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-02-01 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190201_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='inn_plat',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='\u0418\u041d\u041d \u041f\u043b\u0430\u0442\u0435\u043b\u044c\u0449\u0438\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='account',
            name='inn_pol',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='\u0418\u041d\u041d \u0413\u0440\u0443\u0437\u043e\u043f\u043e\u043b\u0443\u0447\u0430\u0442\u0435\u043b\u044f'),
        ),
        migrations.AlterField(
            model_name='account',
            name='kpp_plat',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='\u041a\u041f\u041f \u041f\u043b\u0430\u0442\u0435\u043b\u044c\u0449\u0438\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='account',
            name='kpp_pol',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='\u041a\u041f\u041f \u0413\u0440\u0443\u0437\u043e\u043f\u043e\u043b\u0443\u0447\u0430\u0442\u0435\u043b\u044f'),
        ),
    ]
