# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-07-03 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20190314_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='zavodchik',
            field=models.BooleanField(default=False, verbose_name='\u0417\u0430\u0432\u043e\u0434\u0447\u0438\u043a/\u043f\u0438\u0442\u043e\u043c\u043d\u0438\u043a'),
        ),
    ]
