# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-07-06 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='basket_of_goods',
            field=models.BooleanField(default=False, verbose_name='\u0441\u043a\u0440\u044b\u0442\u044c \u041a\u043e\u0440\u0437\u0438\u043d\u0443 \u0434\u043e\u0431\u0440\u0430'),
        ),
    ]
