# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-08-16 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='inn_cashier',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='\u0418\u041d\u041d \u041a\u0430\u0441\u0441\u0438\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_employed',
            field=models.BooleanField(default=False, verbose_name='\u0422\u0440\u0443\u0434\u043e\u0443\u0441\u0442\u0440\u043e\u0435\u043d'),
        ),
        migrations.AddField(
            model_name='account',
            name='name_cashier',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u041a\u0430\u0441\u0441\u0438\u0440\u0430'),
        ),
    ]
