# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-08-23 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_account_basket_of_goods'),
        ('core', '0027_auto_20210816_1354'),
    ]

    operations = [
    ]
