# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-08-26 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_merge_20210823_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='inn_cashier',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u0418\u041d\u041d \u041a\u0430\u0441\u0441\u0438\u0440\u0430'),
        ),
    ]
