# Generated by Django 4.2.11 on 2024-03-25 13:18

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20220512_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='account',
            name='usersource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.usersource', verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='hash',
            field=models.CharField(max_length=32, verbose_name='Хеш текста'),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('1', 'Ожидает модерации'), ('2', 'Опубликованный'), ('3', 'Отключенная')], default='2', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='static',
            name='menu',
            field=models.CharField(choices=[('1', 'Нет в меню'), ('2', 'Раздел основного меню'), ('3', 'Дополнительное меню №1'), ('4', 'Дополнительное меню №2'), ('5', 'Дополнительное меню №3')], default=1, max_length=1, verbose_name='Расположение раздела'),
        ),
    ]
