# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-09-20 13:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0081_auto_20200820_1417'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0442\u043a\u0440\u044b\u0442\u0438\u044f')),
                ('close_date', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0437\u0430\u043a\u0440\u044b\u0442\u0438\u044f')),
                ('cash', models.FloatField(default=0, verbose_name='\u0414\u0435\u043d\u0435\u0433 \u0432 \u043a\u0430\u0441\u0441\u0435 \u043f\u0440\u0438 \u0437\u0430\u043a\u0440\u044b\u0442\u0438\u0438')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sklad_dury_manager', to=settings.AUTH_USER_MODEL, verbose_name='\u041a\u043b\u0430\u0434\u043e\u0432\u0449\u0438\u043a')),
                ('warehouse', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sklad_durt_warehouse', to='catalog.WareHouse', verbose_name='\u0421\u043a\u043b\u0430\u0434')),
            ],
            options={
                'verbose_name': '\u0441\u043c\u0435\u043d\u0430',
                'verbose_name_plural': '\u0421\u043c\u0435\u043d\u044b',
            },
        ),
        migrations.CreateModel(
            name='Encashment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(verbose_name='\u041a\u043e\u043b-\u0432\u043e \u0434\u0435\u043d\u0435\u0433')),
                ('comment', models.TextField(verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438 \u0432\u0440\u0435\u043c\u044f')),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.Duty', verbose_name='\u0421\u043c\u0435\u043d\u0430')),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': '\u0418\u043d\u043a\u0430\u0441\u0441\u0430\u0446\u0438\u044f/\u041f\u043e\u0441\u0442\u0443\u043f\u043b\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u0418\u043d\u043a\u0430\u0441\u0441\u0430\u0446\u0438\u0438/\u041f\u043e\u0441\u0442\u0443\u043f\u043b\u0435\u043d\u0438\u044f',
            },
        ),
    ]
