# Generated by Django 3.2.25 on 2024-05-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0004_alter_duty_manager_alter_duty_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='encashment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
