# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-07-12 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kassa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='open_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
