# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-07-14 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kassa', '0002_auto_20200712_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duty',
            options={'verbose_name': '\u0441\u043c\u0435\u043d\u0430', 'verbose_name_plural': '\u0421\u043c\u0435\u043d\u044b'},
        ),
    ]
