# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-07-15 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0057_auto_20200715_1730'),
        ('kassa', '0003_auto_20200714_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.WareHouse'),
        ),
    ]
