# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-07-19 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kassa', '0004_duty_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='type',
            field=models.IntegerField(choices=[(0, '\u0421\u043a\u043b\u0430\u0434'), (1, '\u0420\u043e\u0437\u043d\u0438\u0446\u0430')], default=0, verbose_name='\u0422\u0438\u043f \u0441\u043a\u043b\u0430\u0434\u0430'),
        ),
    ]
