# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-07-19 20:32
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Group


def create_group(apps, schema_editor):
    group = Group.objects.filter(id=3).first()
    if not group:
        group = Group(name=u'Продавцы')
        group.save()


class Migration(migrations.Migration):
    dependencies = [
        ('kassa', '0006_remove_duty_type'),
    ]

    operations = [
        migrations.RunPython(create_group)
    ]
