# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-07-20 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kassa', '0007_auto_20200719_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duty',
            old_name='money',
            new_name='cash',
        ),
        migrations.AddField(
            model_name='duty',
            name='non_cash',
            field=models.FloatField(default=0),
        ),
    ]
