# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-08-11 16:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kassa', '0009_encashment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encashment',
            options={'ordering': ['-date'], 'verbose_name': '\u0418\u043d\u043a\u0430\u0441\u0441\u0430\u0446\u0438\u044f/\u041f\u043e\u0441\u0442\u0443\u043f\u043b\u0435\u043d\u0438\u0435', 'verbose_name_plural': '\u0418\u043d\u043a\u0430\u0441\u0441\u0430\u0446\u0438\u0438/\u041f\u043e\u0441\u0442\u0443\u043f\u043b\u0435\u043d\u0438\u044f'},
        ),
        migrations.AlterField(
            model_name='duty',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041a\u0430\u0441\u0441\u0438\u0440'),
        ),
        migrations.AlterField(
            model_name='duty',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.WareHouse', verbose_name='\u0421\u043a\u043b\u0430\u0434'),
        ),
        migrations.AlterField(
            model_name='encashment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438 \u0432\u0440\u0435\u043c\u044f'),
        ),
    ]
