# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-08-20 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kassa', '0012_auto_20200812_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='cash',
            field=models.FloatField(default=0, verbose_name='\u0414\u0435\u043d\u0435\u0433 \u0432 \u043a\u0430\u0441\u0441\u0435'),
        ),
        migrations.AlterField(
            model_name='duty',
            name='close_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0437\u0430\u043a\u0440\u044b\u0442\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='duty',
            name='non_cash',
            field=models.FloatField(default=0, verbose_name='\u041f\u0440\u043e\u0434\u0430\u043d\u043e \u0437\u0430 \u0431\u0435\u0437\u043d\u0430\u043b'),
        ),
        migrations.AlterField(
            model_name='duty',
            name='open_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0442\u043a\u0440\u044b\u0442\u0438\u044f'),
        ),
    ]
