# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-11-09 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kassa', '0013_auto_20200820_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='encashment',
            name='type',
            field=models.IntegerField(choices=[(1, '\u0418\u0437\u044a\u044f\u0442\u0438\u0435'), (2, '\u0417\u041f'), (3, '\u0412\u043e\u0437\u0432\u0440\u0430\u0442 \u043a\u043b\u0438\u0435\u043d\u0442\u0443'), (4, '\u041f\u0440\u043e\u0447\u0435\u0435')], default=1, verbose_name='\u0422\u0438\u043f'),
        ),
    ]
