# -*- coding: utf-8 -*-
"""
Django settings for kostochka38 project.

Generated by 'django-admin startproject' using Django 1.9.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_NAME = 'kostochka38'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%dfgghdRE%^U&DGFJ^garjjfghdfsfgsdfgsdhyd&XFGhDfgher6udfgDgfHdtFsd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.getenv('DEBUG', False))

# ALLOWED_HOSTS = ['kostochka38', 'www.kostochka38', 'localhost', 'www.localhost', '127.0.0.1']
ALLOWED_HOSTS = ['*']

PREPEND_NOT_WWW = True

# Application definition

INSTALLED_APPS = [
    'django_admin_inline_paginator.apps.DjangoAdminInlinePaginatorConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sitemaps',
    
    'admin_tools',
    'admin_tools.theming',
    'admin_tools.menu',
    'admin_tools.dashboard',

    'imagekit',
    'ckeditor',
    'ckeditor_uploader',
    'captcha',
    'pytils',
    'reversion',
    'compressor',
    # 'django_tables2',
    'chart_tools',
    'qsstats',

    'braces',
    # 'recommends',
    # 'recommends.storages.djangoorm',
    # 'django_celery_results',
    # 'django_celery_beat',
    'mailer',
    'campaign',
    'sberbank',
    'adminsortable2',

    'kassa',
    'sklad',
    'core',
    'news',
    'catalog'
]

MIDDLEWARE = [    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 'kostochka38.middleware.custom.GoToPathWithoutWWW',
    # 'kostochka38.middleware.custom.BrokenLinkEmailsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.common.BrokenLinkEmailsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'core.middleware.TokenAuthenticationMiddleware',
    # 'core.middleware.CookieNotificationMiddleware',
    # 'kostochka38.middleware.ValidateBrowser',
    # 'removewww.middleware.RemoveWwwMiddleware',
    # 'core.middleware.ChosenAdminMiddleware',
    # 'reversion.middleware.RevisionMiddleware',
]
REMOVE_WWW = True

#CSRF_COOKIE_DOMAIN = ['.kostochka38.ru', 'localhost']
#CSRF_TRUSTED_ORIGINS = ['.kostochka38.ru', 'localhost']

ROOT_URLCONF = 'kostochka38.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR,'adminsortable', 'templates'),
            ''
        ],
        # 'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'kostochka38.context_processors.test_permitions',
                'kostochka38.context_processors.menu',
                'kostochka38.context_processors.announcement'
            ],
            'loaders': [
                'admin_tools.template_loaders.Loader',
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ]
        },

    },
]

WSGI_APPLICATION = 'kostochka38.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DB_USER = os.getenv('DB_USER')
DB_PASS = os.getenv('DB_PASS')
DB_HOST = os.getenv('DB_HOST')
DB_NAME = os.getenv('DB_NAME')
DB_PORT = os.getenv('DB_PORT')
DB_PORT = 3306

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db',
        'USER': 'root',
        'PASSWORD': "root",
        'HOST': "127.0.0.1",
        'PORT': "3306",
        'OPTIONS': {
            'init_command': 'SET default_storage_engine=INNODB, foreign_key_checks = 0',
            'charset': 'utf8',
        },
        'TEST': {
            'NAME': 'db',
        }
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'db',
#         'USER': 'root',
#         'PASSWORD': 'root',
#         'HOST': 'dbpg',
#         'PORT': '5432',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

TIME_ZONE = 'Asia/Irkutsk'
LANGUAGE_CODE = 'ru'
USE_I18N = True
# USE_L10N = True
DECIMAL_SEPARATOR = ','

USE_TZ = False

ADMINS = (
    ('Vanger', 'support@kostochka38.ru'),
    ('ZhenyaTrukhin', 'jenya-trukhin@mail.ru')
)
MANAGERS = ADMINS


AUTH_USER_MODEL = 'core.Account'
SESSION_COOKIE_AGE = 15536000

SITE_ID = 1
ALSO_BUY_SITE_ID = 2
RECOMMENDS_TASK_CRONTAB = {'hour': '*/2400'}


# # Celery settings
# CELERY_BROKER_URL = 'amqp://guest:guest@localhost//'
# # CELERY_SEND_EVENTS = True
# CELERY_ACCEPT_CONTENT = ['json']
# CELERY_RESULT_BACKEND = ''
# CELERY_TASK_SERIALIZER = 'json'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'
CKEDITOR_UPLOAD_SLUGIFY_FILENAME = True

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
]

CKEDITOR_CONFIGS = {
    'default': {
        "removePlugins": "stylesheetparser",
        'allowedContent': True,
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Maximize', '-', 'Source', '-', 'autoFormat', 'CommentSelectedRange', 'UncommentSelectedRange'],
            ['TextColor', 'FontSize', 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat'],
            ['NumberedList', 'BulletedList', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['insert', 'Image', 'Table', 'SpecialChar'],
        ],
        'width': 1000,
        'height': 120,
        'extraPlugins': ','.join(
            [
                'autogrow',
            ]),


    },
}


# RECOMMENDS_STORAGE_BACKEND = 'catalog.recommends_storage.DjangoStorage'

ADMIN_TOOLS_MENU = 'kostochka38.menu.CustomMenu'
ADMIN_TOOLS_INDEX_DASHBOARD = 'kostochka38.dashboard.CustomIndexDashboard'
ADMIN_TOOLS_APP_INDEX_DASHBOARD = 'kostochka38.dashboard.CustomAppIndexDashboard'
# ADMIN_TOOLS_THEMING_CSS = 'css/theming.css'

CAMPAIGN_BACKEND = 'core.django_mailer_backend'
MAILER_EMAIL_MAX_BATCH = 500
MAILER_EMAIL_THROTTLE = 0


MIN_SUMM_FREE_SHIPING = 1000  # сумма для бесплатной доставки
DOSTAVKA = 150  # стоимость доставки
REVENUE = 1.09  # наценка
SIBCAT_REVENUE = 1.3
BANK_COMMISSION = 0.98
BANK_COMMISSION_ONLINE = 0.98

SENDER_EMAIL = 'Kostochka38.ru <noreply@kostochka38.ru>'
DEFAULT_FROM_EMAIL = 'Kostochka38.ru <noreply@kostochka38.ru>'

ORDER_EMAIL = 'pochta@kostochka38.ru'
REPLY_EMAIL = 'pochta@kostochka38.ru'
REVIEW_EMAIL = 'pochta@kostochka38.ru'

SUPPORT_EMAIL = 'pochta@kostochka38.ru'
SERVER_EMAIL = 'Kostochka38.ru <support@kostochka38.ru>'

PATH_TO_FONTS = os.path.join(BASE_DIR, 'core', 'static')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        }
    },
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        }
    },
    'loggers': {
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': True,
        },
        'kassa': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'catalog': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'core': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'campaign': {
            'handlers': ['console'],
            'level': 'INFO',
        }
    }
}

CAIROTEXT_DIR = 'cairotext_cache'
CAIROTEXT_PRESETS = dict(
    fancy=dict(
        font='Open Sans',
        size=24,
        background=(0, 0, 0, 0),
        color='#3F3F3F',
        height=33,
        baseline=28)
)

CAPTCHA_NOISE_FUNCTIONS = ('captcha.helpers.noise_arcs', )
CAPTCHA_TIMEOUT = 15
CAPTCHA_LETTER_ROTATION = (-30, 30)
# CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.random_number_challenge'
# LOCAL = bool(int(os.getenv('LOCAL', False)))
LOCAL = True
F_SHOP_ID = 'fUYyLN'
F_SECRET_KEY = 'ysvxhxZ7KX'

EMAIL_BACKEND = "mailer.backend.DbBackend"
MAILER_EMAIL_BACKEND = "sgbackend.SendGridBackend"
SENDGRID_API_KEY = "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"

TYPE_CHECKING = False

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

try:
    from kostochka38.local_settings import *
except ImportError:
    pass
