# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filter',
            options={'ordering': ['sort', 'title'], 'verbose_name': '\u0424\u0438\u043b\u044c\u0442\u0440', 'verbose_name_plural': '\u0424\u0438\u043b\u044c\u0442\u0440\u044b'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['deckitem__producer__title', 'deckitem__title', 'real_price'], 'verbose_name': '\u0412\u0435\u0441/\u0442\u0438\u043f \u0441 \u0446\u0435\u043d\u043e\u0439', 'verbose_name_plural': '\u0412\u0435\u0441/\u0442\u0438\u043f \u0441 \u0446\u0435\u043d\u043e\u0439'},
        ),
    ]
