# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_logingcourierfinish'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoZakad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='outsidezakaz',
            name='store',
            field=models.IntegerField(choices=[(0, 'Kostochka38'), (1, 'bbox38'), (2, 'kupi38'), (3, 'motobro38'), (4, 'zdoroveikin')], verbose_name='\u041c\u0430\u0433\u0430\u0437\u0438\u043d'),
        ),
    ]
