# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-11 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20160711_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autozakaz',
            name='last_order',
            field=models.DateTimeField(blank=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0435\u0433\u043e \u0430\u0432\u0442\u043e\u043f\u043e\u0432\u0442\u043e\u0440\u0430'),
        ),
    ]
