# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-04 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_zakaz_autocreate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=128, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0437\u0430\u043a\u0430\u0437\u0430')),
                ('order', models.PositiveIntegerField(verbose_name='\u041f\u043e\u0440\u044f\u0434\u043a\u043e\u0432\u044b\u0439 \u043d\u043e\u043c\u0435\u0440')),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name': '\u0421\u043e\u0440\u0442\u0438\u0440\u043e\u0432\u043a\u0430 \u0437\u0430\u043a\u0430\u0437\u043e\u0432 \u043a\u0443\u0440\u044c\u0435\u0440\u0430',
                'verbose_name_plural': '\u0421\u043e\u0440\u0442\u0438\u0440\u043e\u0432\u043a\u0430 \u0437\u0430\u043a\u0430\u0437\u043e\u0432 \u043a\u0443\u0440\u044c\u0435\u0440\u0430',
            },
        ),
    ]
