# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_outsidezakazstatuslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.IntegerField(blank=True, null=True, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430 %')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='\u0414\u043e')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0421\u043a\u0438\u0434\u043a\u0430 \u043d\u0430 \u0442\u043e\u0432\u0430\u0440',
                'verbose_name_plural': '\u0421\u043a\u0438\u0434\u043a\u0438 \u043d\u0430 \u0442\u043e\u0432\u0430\u0440',
            },
        ),
        migrations.AlterField(
            model_name='deckitem',
            name='availability',
            field=models.IntegerField(choices=[(0, '\u041d\u0435\u0442 \u0432 \u043d\u0438\u043b\u0438\u0447\u0438\u0438'), (3, '\u0412 \u043d\u0430\u043b\u0438\u0447\u0438\u0438 \u0443 \u043f\u043e\u0441\u0442\u0430\u0432\u0449\u0438\u043a\u0430'), (10, '\u0412 \u043d\u0430\u043b\u0438\u0447\u0438\u0438 \u043d\u0430 \u0441\u043a\u043b\u0430\u0434\u0435')], default=3, verbose_name='\u041d\u0430\u043b\u0438\u0447\u0438\u0435 \u0442\u043e\u0432\u0430\u0440\u0430'),
        ),
        migrations.AlterField(
            model_name='item',
            name='availability',
            field=models.IntegerField(choices=[(0, '\u041d\u0435\u0442 \u0432 \u043d\u0438\u043b\u0438\u0447\u0438\u0438'), (3, '\u0412 \u043d\u0430\u043b\u0438\u0447\u0438\u0438 \u0443 \u043f\u043e\u0441\u0442\u0430\u0432\u0449\u0438\u043a\u0430'), (10, '\u0412 \u043d\u0430\u043b\u0438\u0447\u0438\u0438 \u043d\u0430 \u0441\u043a\u043b\u0430\u0434\u0435')], default=3, verbose_name='\u041d\u0430\u043b\u0438\u0447\u0438\u0435 \u0442\u043e\u0432\u0430\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='itemsale',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Item', verbose_name=b'\xd1\x82\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x80'),
        ),
    ]
