# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20161005_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempzakazgoods',
            name='sale',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0441\u043a\u0438\u0434\u043a\u0430 %'),
        ),
    ]
