# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-04 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20170129_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsale',
            name='show',
            field=models.BooleanField(default=False, verbose_name='\u041e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c \u0432 \u0440\u0430\u0437\u0434\u0435\u043b\u0435 \u0430\u043a\u0446\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='itemsale',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Item', verbose_name='\u0442\u043e\u0432\u0430\u0440'),
        ),
    ]
