# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-04 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20170204_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='page_link',
            field=models.BooleanField(default=False, verbose_name='\u0412\u043a\u043b\u044e\u0447\u0438\u0442\u044c \u0443\u043d\u0438\u043a\u0430\u043b\u044c\u043d\u0443\u044e \u0441\u0441\u044b\u043b\u043a\u0443'),
            preserve_default=False,
        ),
    ]
