# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-04 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_filter_page_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a h1')),
                ('head_title', models.CharField(blank=True, max_length=512, null=True, verbose_name='<title>')),
                ('meta_descroption', models.CharField(blank=True, max_length=1024, null=True, verbose_name='<descroption>')),
                ('meta_keywords', models.CharField(blank=True, max_length=1024, null=True, verbose_name='<keywords>')),
                ('link_title', models.CharField(blank=True, max_length=512, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a h1')),
                ('footer_view', models.BooleanField(default=False, verbose_name='\u0412\u044b\u0432\u043e\u0434\u0438\u0442\u044c \u0432 \u043f\u043e\u0434\u0432\u0430\u043b\u0435')),
            ],
            options={
                'verbose_name': '\u0423\u043d\u0438\u043a\u0430\u043b\u044c\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u0434\u043b\u044f \u0444\u0438\u043b\u044c\u0442\u0440\u0432',
                'verbose_name_plural': '\u0423\u043d\u0438\u043a\u0430\u043b\u044c\u043d\u044b\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0434\u043b\u044f \u0444\u0438\u043b\u044c\u0442\u0440\u043e\u0432',
            },
        ),
        migrations.AlterField(
            model_name='filter',
            name='page_link',
            field=models.BooleanField(default=False, verbose_name='\u0412\u043a\u043b\u044e\u0447\u0438\u0442\u044c \u0443\u043d\u0438\u043a\u0430\u043b\u044c\u043d\u0443\u044e \u0441\u0441\u044b\u043b\u043a\u0443'),
        ),
        migrations.AddField(
            model_name='filterdescription',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Filter', unique=True, verbose_name='\u0424\u0438\u043b\u044c\u0442\u0440'),
        ),
    ]
