# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20170204_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='page_link',
        ),
        migrations.AddField(
            model_name='filterdescription',
            name='link_url',
            field=models.CharField(default=0, max_length=128, verbose_name='\u0441\u0441\u044b\u043b\u043a\u0430'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentitem',
            name='name',
            field=models.CharField(default=False, max_length=128, verbose_name='\u0418\u043c\u044f'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='name',
            field=models.CharField(default=b'Name', max_length=256, verbose_name='\u0424\u0418\u041e'),
        ),
        migrations.AlterField(
            model_name='filterdescription',
            name='filter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Filter', unique=True, verbose_name='\u0424\u0438\u043b\u044c\u0442\u0440'),
        ),
        migrations.AlterField(
            model_name='filterdescription',
            name='link_title',
            field=models.CharField(default=0, max_length=128, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0441\u044b\u043b\u043a\u0438'),
            preserve_default=False,
        ),
    ]
