# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-09 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20170926_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='real_sum',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='\u041a \u043e\u043f\u043b\u0430\u0442\u0435'),
        ),
    ]
