# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-06 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_auto_20171119_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckitem',
            name='super_description',
            field=models.TextField(blank=True, null=True, verbose_name='\u0421\u0443\u043f\u0435\u0440 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
    ]
