# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-16 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_deckitem_super_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='on_main',
            field=models.BooleanField(default=False, verbose_name='\u041d\u0430 \u0433\u043b\u0430\u0432\u043d\u043e\u0439'),
        ),
        migrations.AlterField(
            model_name='insidezakaz',
            name='status',
            field=models.IntegerField(choices=[(0, '\u041d\u043e\u0432\u044b\u0439'), (1, '\u041f\u043e\u0434 \u0437\u0430\u043a\u0430\u0437'), (2, '\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0430 \u0441\u043e\u0433\u043b\u0430\u0441\u043e\u0432\u0430\u043d\u0430'), (4, '\u0417\u0430\u043a\u0430\u0437 \u043f\u043e\u043b\u0443\u0447\u0435\u043d'), (6, '\u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043d')], default=0, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441'),
        ),
        migrations.AlterField(
            model_name='insidezakazstatuslog',
            name='status',
            field=models.IntegerField(choices=[(0, '\u041d\u043e\u0432\u044b\u0439'), (1, '\u041f\u043e\u0434 \u0437\u0430\u043a\u0430\u0437'), (2, '\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0430 \u0441\u043e\u0433\u043b\u0430\u0441\u043e\u0432\u0430\u043d\u0430'), (4, '\u0417\u0430\u043a\u0430\u0437 \u043f\u043e\u043b\u0443\u0447\u0435\u043d'), (6, '\u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043d')], default=0, verbose_name='\u0441\u0442\u0430\u0442\u0443\u0441 \u0437\u0430\u043a\u0430\u0437\u0430'),
        ),
        migrations.AlterField(
            model_name='outsidezakazstatuslog',
            name='status',
            field=models.IntegerField(choices=[(0, '\u041d\u043e\u0432\u044b\u0439'), (1, '\u041f\u043e\u0434 \u0437\u0430\u043a\u0430\u0437'), (2, '\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0430 \u0441\u043e\u0433\u043b\u0430\u0441\u043e\u0432\u0430\u043d\u0430'), (4, '\u0417\u0430\u043a\u0430\u0437 \u043f\u043e\u043b\u0443\u0447\u0435\u043d'), (6, '\u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043d')], default=0, verbose_name='\u0441\u0442\u0430\u0442\u0443\u0441 \u0437\u0430\u043a\u0430\u0437\u0430'),
        ),
    ]
