# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-01-12 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_filter_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAvailabilityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.IntegerField(choices=[(0, '\u041d\u0435\u0442 \u0432 \u043d\u0430\u043b\u0438\u0447\u0438\u0438'), (3, '\u0412 \u043d\u0430\u043b\u0438\u0447\u0438\u0438 \u0443 \u043f\u043e\u0441\u0442\u0430\u0432\u0449\u0438\u043a\u0430'), (10, '\u0412 \u043d\u0430\u043b\u0438\u0447\u0438\u0438 \u043d\u0430 \u0441\u043a\u043b\u0430\u0434\u0435')], verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441 \u043d\u0430\u043b\u0438\u0447\u0438\u044f')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043c\u0435\u043d\u044b')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Item', verbose_name='\u0412\u0435\u0441/\u0422\u0438\u043f \u0441 \u0446\u0435\u043d\u043e\u0439')),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': '\u041b\u043e\u0433 \u0441\u0442\u0430\u0442\u0443\u0441\u043e\u0432 \u043d\u0430\u043b\u0438\u0447\u0438\u044f',
                'verbose_name_plural': '\u041b\u043e\u0433 \u0441\u0442\u0430\u0442\u0443\u0441\u043e\u0432 \u043d\u0430\u043b\u0438\u0447\u0438\u044f',
            },
        ),
    ]
