# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-02-07 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_auto_20190115_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempzakazgoods',
            name='summ',
            field=models.FloatField(verbose_name='\u0421\u0443\u043c\u043c\u0430'),
        ),
        migrations.AlterField(
            model_name='zakazgoods',
            name='summ',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
