# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-02-07 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_auto_20190207_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='summ',
            field=models.FloatField(verbose_name='\u0421\u0443\u043c\u043c\u0430 \u0437\u0430\u043a\u0430\u0437\u0430'),
        ),
    ]
