# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-03-14 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_auto_20190207_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='margin_opt',
            field=models.FloatField(blank=True, null=True, verbose_name='\u041d\u0430\u0446\u0435\u043d\u043a\u0430 \u0434\u043b\u044f \u043c\u0430\u0433\u0430\u0437\u0438\u043d\u043e\u0432'),
        ),
        migrations.AddField(
            model_name='producer',
            name='margin_zavodchiki',
            field=models.FloatField(blank=True, null=True, verbose_name='\u041d\u0430\u0446\u0435\u043d\u043a\u0430 \u0434\u043b\u044f \u043f\u0438\u0442\u043e\u043c\u043d\u0438\u043a\u043e\u0432'),
        ),
    ]
