# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-10-15 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_auto_20191015_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckitem',
            name='segment_new',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Segment', verbose_name='\u0421\u0435\u0433\u043c\u0435\u043d\u0442'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insidezakaz',
            name='segment_new',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Segment', verbose_name='\u041f\u043e\u0441\u0442\u0430\u0432\u0449\u0438\u043a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parserlog',
            name='segment_new',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Segment', verbose_name='\u0421\u0435\u0433\u043c\u0435\u043d\u0442'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priceparser',
            name='segment_new',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Segment', verbose_name='\u041f\u043e\u0441\u0442\u0430\u0432\u0449\u0438\u043a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producer',
            name='segment_new',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Segment', verbose_name='\u0421\u0435\u0433\u043c\u0435\u043d\u0442'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saletable',
            name='segment_new',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Segment', verbose_name='\u041f\u043e\u0441\u0442\u0430\u0432\u0449\u0438\u043a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendoraccount',
            name='segment_new',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Segment', verbose_name='\u041f\u043e\u0441\u0442\u0430\u0432\u0449\u0438\u043a'),
            preserve_default=False,
        ),
    ]
