# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-10-16 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_auto_20191015_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segment',
            options={'ordering': ['order', 'title'], 'verbose_name': '\u043f\u043e\u0441\u0442\u0430\u0432\u0449\u0438\u043a', 'verbose_name_plural': '\u041f\u043e\u0441\u0442\u0430\u0432\u0449\u0438\u043a\u0438'},
        ),
        migrations.AddField(
            model_name='segment',
            name='in_balans',
            field=models.BooleanField(default=False, verbose_name='\u0412 \u0431\u0430\u043b\u0430\u043d\u0441\u0435'),
        ),
        migrations.AddField(
            model_name='segment',
            name='in_statistics',
            field=models.BooleanField(default=False, verbose_name='\u0412 \u0441\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0435'),
        ),
        migrations.AddField(
            model_name='segment',
            name='order',
            field=models.PositiveIntegerField(default=99, verbose_name='\u0421\u043e\u0440\u0442\u0438\u0440\u043e\u0432\u043a\u0430'),
        ),
    ]
