# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-10-16 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0043_auto_20191016_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deckitem',
            name='segment',
        ),
        migrations.RemoveField(
            model_name='insidezakaz',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='parserlog',
            name='segment',
        ),
        migrations.RemoveField(
            model_name='priceparser',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='segment',
        ),
        migrations.RemoveField(
            model_name='saletable',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='vendoraccount',
            name='supplier',
        ),
    ]
