# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-12-18 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0046_priceparser_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='need_quantity',
            field=models.BooleanField(default=False, verbose_name='\u0423\u0447\u0438\u0442\u044b\u0432\u0430\u0442\u044c \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e?'),
        ),
        migrations.AddField(
            model_name='segment',
            name='num_article',
            field=models.IntegerField(blank=True, null=True, verbose_name='#article'),
        ),
        migrations.AddField(
            model_name='segment',
            name='num_check_empty',
            field=models.IntegerField(blank=True, null=True, verbose_name='#empty'),
        ),
        migrations.AddField(
            model_name='segment',
            name='num_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='#code'),
        ),
        migrations.AddField(
            model_name='segment',
            name='num_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='#price'),
        ),
        migrations.AddField(
            model_name='segment',
            name='num_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='#quantity'),
        ),
        migrations.AddField(
            model_name='segment',
            name='num_start',
            field=models.IntegerField(blank=True, null=True, verbose_name='#start'),
        ),
        migrations.AddField(
            model_name='segment',
            name='num_title',
            field=models.IntegerField(blank=True, null=True, verbose_name='#title'),
        ),
        migrations.AddField(
            model_name='segment',
            name='what_status',
            field=models.IntegerField(choices=[(0, '\u041d\u0435\u0442 \u0432 \u043d\u0430\u043b\u0438\u0447\u0438\u0438'), (3, '\u0412 \u043d\u0430\u043b\u0438\u0447\u0438\u0438 \u0443 \u043f\u043e\u0441\u0442\u0430\u0432\u0449\u0438\u043a\u0430'), (10, '\u0412 \u043d\u0430\u043b\u0438\u0447\u0438\u0438 \u043d\u0430 \u0441\u043a\u043b\u0430\u0434\u0435'), (20, '\u041f\u043e\u0434 \u0437\u0430\u043a\u0430\u0437')], default=3, verbose_name='\u041a\u0430\u043a\u043e\u0439 \u0441\u0442\u0430\u0442\u0443\u0441?'),
        ),
        migrations.AddField(
            model_name='segment',
            name='word_to_quantity',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u0421\u043b\u043e\u0432\u043e \u0434\u043b\u044f \u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u0430'),
        ),
    ]
