# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-12-18 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0047_auto_20191218_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceparser',
            name='result',
        ),
        migrations.AddField(
            model_name='priceparser',
            name='error',
            field=models.TextField(blank=True, null=True, verbose_name='\u041e\u0448\u0438\u0431\u043a\u0438'),
        ),
        migrations.AddField(
            model_name='priceparser',
            name='result_1',
            field=models.TextField(blank=True, null=True, verbose_name='\u0422\u043e\u0432\u0430\u0440 \u043d\u0430\u0448\u0435\u043b\u0441\u044f, \u0446\u0435\u043d\u0430 \u0438\u0437\u043c\u0435\u043d\u0438\u043b\u0430\u0441\u044c'),
        ),
        migrations.AddField(
            model_name='priceparser',
            name='result_2',
            field=models.TextField(blank=True, null=True, verbose_name='\u041d\u043e\u0432\u044b\u0435 \u044d\u043b\u0435\u043c\u0435\u043d\u0442\u044b'),
        ),
        migrations.AddField(
            model_name='priceparser',
            name='result_3',
            field=models.TextField(blank=True, null=True, verbose_name='\u041f\u043e\u0442\u0435\u0440\u044f\u043d\u043d\u044b\u0439 \u0442\u043e\u0432\u0430\u0440 (\u0435\u0441\u0442\u044c \u0432 \u0431\u0430\u0437\u0435, \u043d\u0435\u0442 \u0432 \u043f\u0440\u0430\u0439\u0441\u0435)'),
        ),
        migrations.AddField(
            model_name='priceparser',
            name='result_4',
            field=models.TextField(blank=True, null=True, verbose_name='\u0422\u043e\u0432\u0430\u0440 \u043d\u0430\u0448\u0435\u043b\u0441\u044f, \u0446\u0435\u043d\u0430 \u043d\u0435 \u0438\u0437\u043c\u0435\u043d\u0438\u043b\u0430\u0441\u044c (\u041d\u041e \u0422\u041e\u0412\u0410\u0420 \u041d\u0415 \u0410\u041a\u0422\u0418\u0412\u041d\u042b\u0419)'),
        ),
        migrations.AddField(
            model_name='priceparser',
            name='result_5',
            field=models.TextField(blank=True, null=True, verbose_name='\u0422\u043e\u0432\u0430\u0440 \u043d\u0430\u0448\u0435\u043b\u0441\u044f, \u0446\u0435\u043d\u0430 \u043d\u0435 \u0438\u0437\u043c\u0435\u043d\u0438\u043b\u0430\u0441\u044c'),
        ),
        migrations.AddField(
            model_name='segment',
            name='word_to_quantity_small',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u0421\u043b\u043e\u0432\u043e \u0434\u043b\u044f \u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u0430 \u043c\u0430\u043b\u043e'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='word_to_quantity',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u0421\u043b\u043e\u0432\u043e \u0434\u043b\u044f \u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u0430 \u043c\u043d\u043e\u0433\u043e'),
        ),
    ]
