# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-12-18 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0048_auto_20191218_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='need_special_article',
            field=models.BooleanField(default=False, verbose_name='\u041d\u0435\u0432\u0438\u0434\u0438\u043c\u044b\u0435 \u0430\u0440\u0442\u0438\u043a\u0443\u043b\u044b?'),
        ),
    ]
