# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-12-29 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0049_segment_need_special_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='logingcourierfinish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='\u0421\u043a\u0440\u0438\u043d'),
        ),
    ]
