# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-07-12 15:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0054_item_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashier_zakaz_set', to=settings.AUTH_USER_MODEL, verbose_name='\u041a\u0430\u0441\u0441\u0438\u0440'),
        ),
    ]
