# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-07-14 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    WareHouseModel = apps.get_model('catalog', 'Warehouse')
    w1 = WareHouseModel(name=u'Склад 1')
    w1.save()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0055_zakaz_cashier'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.IntegerField(default=0, verbose_name=b'\xd0\x9e\xd1\x81\xd1\x82\xd0\xb0\xd1\x82\xd0\xbe\xd0\xba')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Item', verbose_name=b'\xd0\x92\xd0\xb5\xd1\x81/\xd0\xa2\xd0\xb8\xd0\xbf \xd1\x82\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x80\xd0\xb0')),
            ],
            options={
                'verbose_name': '\u041e\u0441\u0442\u0430\u0442\u043e\u043a',
                'verbose_name_plural': '\u041e\u0441\u0442\u0430\u0442\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 \xd1\x81\xd0\xba\xd0\xbb\xd0\xb0\xd0\xb4\xd0\xb0')),
                ('full_name', models.TextField(blank=True, null=True, verbose_name=b'\xd0\x9f\xd0\xbe\xd0\xbb\xd0\xbd\xd0\xbe\xd0\xb5 \xd0\xbd\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'\xd0\x90\xd0\xb4\xd1\x80\xd0\xb5\xd1\x81')),
                ('phone', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'\xd0\x9d\xd0\xbe\xd0\xbc\xd0\xb5\xd1\x80 \xd1\x82\xd0\xb5\xd0\xbb\xd0\xb5\xd1\x84\xd0\xbe\xd0\xbd\xd0\xb0')),
                ('working_mode_start', models.TimeField(blank=True, null=True, verbose_name=b'\xd0\x9d\xd0\xb0\xd1\x87\xd0\xb0\xd0\xbb\xd0\xbe \xd1\x80\xd0\xb0\xd0\xb1\xd0\xbe\xd1\x82\xd1\x8b')),
                ('working_mode_end', models.TimeField(blank=True, null=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xb5\xd0\xbd\xd1\x86 \xd1\x80\xd0\xb0\xd0\xb1\xd0\xbe\xd1\x82\xd1\x8b')),
            ],
        ),
        migrations.AddField(
            model_name='leftitem',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.WareHouse', verbose_name=b'\xd0\xa1\xd0\xba\xd0\xbb\xd0\xb0\xd0\xb4'),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
