# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-07-15 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0056_auto_20200714_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': '\u0421\u043a\u043b\u0430\u0434', 'verbose_name_plural': '\u0421\u043a\u043b\u0430\u0434\u044b'},
        ),
    ]
