# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-07-15 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0057_auto_20200715_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.WareHouse', verbose_name=b'\xd0\xa1\xd0\xba\xd0\xbb\xd0\xb0\xd0\xb4'),
        ),
    ]
