# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-07-16 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0058_zakaz_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='insidezakaz',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.WareHouse', verbose_name='\u0421\u043a\u043b\u0430\u0434'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.WareHouse', verbose_name=b'\xd0\xa1\xd0\xba\xd0\xbb\xd0\xb0\xd0\xb4'),
        ),
    ]
