# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-07-16 13:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0059_auto_20200716_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Item')),
            ],
            options={
                'verbose_name': '\u0422\u043e\u0432\u0430\u0440 \u043f\u0435\u0440\u0435\u043c\u0435\u0449\u0435\u043d\u0438\u044f',
                'verbose_name_plural': '\u0422\u043e\u0432\u0430\u0440\u044b \u043f\u0435\u0440\u0435\u043c\u0435\u0449\u0435\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='MovementOfGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_paid', models.BooleanField()),
                ('delivery_date', models.DateField()),
                ('creation_date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, '\u041d\u043e\u0432\u043e\u0435'), (1, '\u0421\u043e\u0431\u0440\u0430\u043d\u043e'), (2, '\u0423 \u043a\u0443\u0440\u044c\u0435\u0440\u0430'), (3, '\u041a\u0443\u0440\u044c\u0435\u0440 \u0432\u044b\u0435\u0445\u0430\u043b'), (4, '\u0414\u043e\u0441\u0442\u0430\u0432\u043b\u0435\u043d\u043e'), (5, '\u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u043e')], default=0)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('warehouse_giving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_giving', to='catalog.WareHouse')),
                ('warehouse_recieving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_recieving', to='catalog.WareHouse')),
            ],
            options={
                'verbose_name': '\u041f\u0435\u0440\u0435\u043c\u0435\u0449\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u041f\u0435\u0440\u0435\u043c\u0435\u0449\u0435\u043d\u0438\u044f',
            },
        ),
        migrations.AddField(
            model_name='goodsinmovement',
            name='movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.MovementOfGoods'),
        ),
    ]
