# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-07-16 14:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0060_auto_20200716_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementStatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '\u041d\u043e\u0432\u043e\u0435'), (1, '\u0421\u043e\u0431\u0440\u0430\u043d\u043e'), (2, '\u0423 \u043a\u0443\u0440\u044c\u0435\u0440\u0430'), (3, '\u041a\u0443\u0440\u044c\u0435\u0440 \u0432\u044b\u0435\u0445\u0430\u043b'), (4, '\u0414\u043e\u0441\u0442\u0430\u0432\u043b\u0435\u043d\u043e'), (5, '\u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u043e')], default=0, verbose_name=b'\xd0\xa1\xd1\x82\xd0\xb0\xd1\x82\xd1\x83\xd1\x81')),
                ('date', models.DateField(auto_now_add=True, verbose_name='\u041a\u043e\u0433\u0434\u0430 \u0438\u0437\u043c\u0435\u043d\u0438\u043b')),
            ],
            options={
                'verbose_name': '\u041b\u043e\u0433 \u0441\u0442\u0430\u0442\u0443\u0441\u0430 \u043f\u0435\u0440\u0435\u043c\u0435\u0449\u0435\u043d\u0438\u044f',
                'verbose_name_plural': '\u041b\u043e\u0433\u0438 \u0441\u0442\u0430\u0442\u0443\u0441\u0430 \u043f\u0435\u0440\u0435\u043c\u0435\u0449\u0435\u043d\u0438\u044f',
            },
        ),
        migrations.AlterField(
            model_name='movementofgoods',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xd0\x9a\xd1\x83\xd1\x80\xd1\x8c\xd0\xb5\xd1\x80'),
        ),
        migrations.AlterField(
            model_name='movementofgoods',
            name='courier_paid',
            field=models.BooleanField(verbose_name=b'\xd0\x9a\xd1\x83\xd1\x80\xd1\x8c\xd0\xb5\xd1\x80 \xd0\xbe\xd0\xbf\xd0\xbb\xd0\xb0\xd1\x87\xd0\xb5\xd0\xbd'),
        ),
        migrations.AlterField(
            model_name='movementofgoods',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd1\x81\xd0\xbe\xd0\xb7\xd0\xb4\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f'),
        ),
        migrations.AlterField(
            model_name='movementofgoods',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xb4\xd0\xbe\xd1\x81\xd1\x82\xd0\xb0\xd0\xb2\xd0\xba\xd0\xb8'),
        ),
        migrations.AlterField(
            model_name='movementofgoods',
            name='status',
            field=models.IntegerField(choices=[(0, '\u041d\u043e\u0432\u043e\u0435'), (1, '\u0421\u043e\u0431\u0440\u0430\u043d\u043e'), (2, '\u0423 \u043a\u0443\u0440\u044c\u0435\u0440\u0430'), (3, '\u041a\u0443\u0440\u044c\u0435\u0440 \u0432\u044b\u0435\u0445\u0430\u043b'), (4, '\u0414\u043e\u0441\u0442\u0430\u0432\u043b\u0435\u043d\u043e'), (5, '\u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u043e')], default=0, verbose_name=b'\xd0\xa1\xd1\x82\xd0\xb0\xd1\x82\xd1\x83\xd1\x81'),
        ),
        migrations.AlterField(
            model_name='movementofgoods',
            name='warehouse_giving',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_giving', to='catalog.WareHouse', verbose_name=b'\xd0\xa1\xd0\xba\xd0\xbb\xd0\xb0\xd0\xb4-\xd0\xbe\xd1\x82\xd0\xbf\xd1\x80\xd0\xb0\xd0\xb2\xd0\xb8\xd1\x82\xd0\xb5\xd0\xbb\xd1\x8c'),
        ),
        migrations.AlterField(
            model_name='movementofgoods',
            name='warehouse_recieving',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_recieving', to='catalog.WareHouse', verbose_name=b'\xd0\xa1\xd0\xba\xd0\xbb\xd0\xb0\xd0\xb4-\xd0\xbf\xd0\xbe\xd0\xbb\xd1\x83\xd1\x87\xd0\xb0\xd1\x82\xd0\xb5\xd0\xbb\xd1\x8c'),
        ),
        migrations.AddField(
            model_name='movementstatuslog',
            name='movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.MovementOfGoods'),
        ),
        migrations.AddField(
            model_name='movementstatuslog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041a\u0442\u043e \u0438\u0437\u043c\u0435\u043d\u0438\u043b'),
        ),
    ]
