# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-07-16 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0061_auto_20200716_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movementofgoods',
            old_name='warehouse_giving',
            new_name='warehouse_donor',
        ),
    ]
