# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-07-16 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0062_auto_20200716_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='cash',
            field=models.FloatField(blank=True, null=True, verbose_name='\u041e\u043f\u043b\u0430\u0447\u0435\u043d\u043e \u043d\u0430\u043b\u0438\u0447\u043d\u044b\u043c\u0438'),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='non_cash',
            field=models.FloatField(blank=True, null=True, verbose_name='\u041e\u043f\u043b\u0430\u0447\u0435\u043d\u043e \u0431\u0435\u0437\u043d\u0430\u043b\u043e\u043c'),
        ),
        migrations.AlterField(
            model_name='outsidezakaz',
            name='paytype',
            field=models.IntegerField(choices=[(0, '\u041d\u0430\u043b\u0438\u0447\u043d\u044b\u043c\u0438 \u043f\u0440\u0438 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u0438'), (1, '\u041a\u0430\u0440\u0442\u043e\u0439 \u043f\u0440\u0438 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u0438'), (3, '\u041f\u0435\u0440\u0435\u0432\u043e\u0434 \u043d\u0430 \u043a\u0430\u0440\u0442\u0443 \u0421\u0431\u0435\u0440\u0431\u0430\u043d\u043a\u0430'), (4, '\u041e\u043f\u043b\u0430\u0442\u0430 \u043e\u043d\u043b\u0430\u0439\u043d'), (5, '\u041d\u0430 \u0440\u0430\u0441\u0447\u0435\u0442\u043d\u044b\u0439 \u0441\u0447\u0435\u0442'), (6, '\u0421\u043c\u0435\u0448\u0430\u043d\u043d\u044b\u0439 \u0442\u0438\u043f')], default=0, verbose_name='\u0421\u043f\u043e\u0441\u043e\u0431 \u043e\u043f\u043b\u0430\u0442\u044b'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='paytype',
            field=models.IntegerField(choices=[(0, '\u041d\u0430\u043b\u0438\u0447\u043d\u044b\u043c\u0438 \u043f\u0440\u0438 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u0438'), (1, '\u041a\u0430\u0440\u0442\u043e\u0439 \u043f\u0440\u0438 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u0438'), (3, '\u041f\u0435\u0440\u0435\u0432\u043e\u0434 \u043d\u0430 \u043a\u0430\u0440\u0442\u0443 \u0421\u0431\u0435\u0440\u0431\u0430\u043d\u043a\u0430'), (4, '\u041e\u043f\u043b\u0430\u0442\u0430 \u043e\u043d\u043b\u0430\u0439\u043d'), (5, '\u041d\u0430 \u0440\u0430\u0441\u0447\u0435\u0442\u043d\u044b\u0439 \u0441\u0447\u0435\u0442'), (6, '\u0421\u043c\u0435\u0448\u0430\u043d\u043d\u044b\u0439 \u0442\u0438\u043f')], default=0, verbose_name='\u0421\u043f\u043e\u0441\u043e\u0431 \u043e\u043f\u043b\u0430\u0442\u044b'),
        ),
    ]
