# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-07-19 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0063_auto_20200716_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='warehouse',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.WareHouse', verbose_name=b'\xd0\xa1\xd0\xba\xd0\xbb\xd0\xb0\xd0\xb4'),
        ),
    ]
