# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-07-19 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0065_auto_20200719_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='type',
            field=models.IntegerField(choices=[(0, '\u0421\u043a\u043b\u0430\u0434'), (1, '\u0420\u043e\u0437\u043d\u0438\u0446\u0430')], default=0, verbose_name=b'\xd0\xa2\xd0\xb8\xd0\xbf \xd1\x81\xd0\xba\xd0\xbb\xd0\xb0\xd0\xb4\xd0\xb0'),
        ),
    ]
