# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-07-20 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0066_warehouse_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservelog',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.WareHouse', verbose_name='\u0421\u043a\u043b\u0430\u0434'),
        ),
    ]
