# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-07-20 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0067_reservelog_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservelog',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='reservelog',
            name='movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.MovementOfGoods', verbose_name='\u041f\u0435\u0440\u0435\u043c\u0435\u0449\u0435\u043d\u0438\u0435'),
        ),
    ]
