# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-08-03 13:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0071_auto_20200802_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='default_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xd0\x9f\xd0\xbe\xd0\xba\xd1\x83\xd0\xbf\xd0\xb0\xd1\x82\xd0\xb5\xd0\xbb\xd1\x8c \xd0\xbf\xd0\xbe-\xd1\x83\xd0\xbc\xd0\xbe\xd0\xbb\xd1\x87\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8e'),
        ),
        migrations.AlterField(
            model_name='movementofgoods',
            name='courier_paid',
            field=models.BooleanField(verbose_name='\u041e\u043f\u043b\u0430\u0447\u0435\u043d\u043e \u043a\u0443\u0440\u044c\u0435\u0440\u0443'),
        ),
    ]
