# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-08-06 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0073_auto_20200803_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='f_response',
            field=models.TextField(blank=True, null=True, verbose_name='\u0424-response'),
        ),
    ]
