# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-08-09 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0076_auto_20200807_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementofgoods',
            name='extra',
            field=models.TextField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439'),
        ),
    ]
