# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-08-09 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0077_movementofgoods_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementstatuslog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u041a\u043e\u0433\u0434\u0430 \u0438\u0437\u043c\u0435\u043d\u0438\u043b'),
        ),
    ]
