# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-08-11 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_auto_20190806_1020'),
        ('catalog', '0078_auto_20200809_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Item', verbose_name='\u0422\u043e\u0432\u0430\u0440')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.MailTemplate', verbose_name='\u0428\u0430\u0431\u043b\u043e\u043d \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0438')),
            ],
            options={
                'verbose_name': '\u0422\u043e\u0432\u0430\u0440 \u0434\u043b\u044f \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0438',
                'verbose_name_plural': '\u0422\u043e\u0432\u0430\u0440\u044b \u0434\u043b\u044f \u0440\u0430\u0441\u0441\u044b\u043b\u043e\u043a',
            },
        ),
    ]
