# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-08-12 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0079_itemmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='pickup_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_warehouse', to='catalog.WareHouse', verbose_name=b'\xd0\x9f\xd1\x83\xd0\xbd\xd0\xba\xd1\x82 \xd0\xb2\xd1\x8b\xd0\xb4\xd0\xb0\xd1\x87\xd0\xb8(\xd0\xbf\xd1\x80\xd0\xb8 \xd1\x81\xd0\xb0\xd0\xbc\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb2\xd0\xbe\xd0\xb7\xd0\xb5)'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='warehouse',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='catalog.WareHouse', verbose_name=b'\xd0\xa1\xd0\xba\xd0\xbb\xd0\xb0\xd0\xb4'),
        ),
    ]
