# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-11-09 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0081_auto_20200820_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='pickup_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_warehouse', to='catalog.WareHouse', verbose_name='\u041f\u0443\u043d\u043a\u0442 \u0432\u044b\u0434\u0430\u0447\u0438(\u043f\u0440\u0438 \u0441\u0430\u043c\u043e\u0432\u044b\u0432\u043e\u0437\u0435)'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='warehouse',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='catalog.WareHouse', verbose_name='\u0421\u043a\u043b\u0430\u0434'),
        ),
    ]
