# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-11-10 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0082_auto_20201109_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='target_sended',
            field=models.BooleanField(default=False, verbose_name='\u0426\u0435\u043b\u0438 \u043e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u044b'),
        ),
    ]
