# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-04-05 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0084_auto_20210326_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filter',
            old_name='ceo_title',
            new_name='seo_title',
        ),
    ]
