# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-04-06 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0085_auto_20210405_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterSitemapLink',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('section', models.CharField(choices=[('dlya-sobak', '\u0414\u043b\u044f \u0441\u043e\u0431\u0430\u043a'), ('dlya-koshek', '\u0414\u043b\u044f \u043a\u043e\u0448\u0435\u043a'), ('dlya-gryzunov-i-harkov', '\u0414\u043b\u044f \u0433\u0440\u044b\u0437\u0443\u043d\u043e\u0432 \u0438 \u0445\u043e\u0440\u044c\u043a\u043e\u0432'), ('dlya-ptiz', '\u0414\u043b\u044f \u043f\u0442\u0438\u0446'), ('dlya-rybok', '\u0414\u043b\u044f \u0440\u044b\u0431\u043e\u043a'), ('dlya-reptiliy', '\u0414\u043b\u044f \u0440\u0435\u043f\u0442\u0438\u043b\u0438\u0439')], max_length=128)),
                ('link', models.CharField(max_length=512)),
                ('title', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=1024)),
                ('keywords', models.CharField(max_length=512)),
                ('h1', models.CharField(max_length=512)),
            ],
        ),
    ]
