# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-04-06 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0086_auto_20210406_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filtersitemaplink',
            name='section',
        ),
    ]
