# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-04-12 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0087_auto_20210406_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='new',
            field=models.BooleanField(default=True, verbose_name='\u041d\u043e\u0432\u0438\u043d\u043a\u0430'),
        ),
    ]
