# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-05-21 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0090_auto_20210509_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='insidezakaz',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='\u041b\u043e\u0433'),
        ),
    ]
