# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-05-31 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0092_auto_20210530_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempzakaz',
            name='availability_changed',
        ),
        migrations.RemoveField(
            model_name='tempzakaz',
            name='summ_changed',
        ),
        migrations.AddField(
            model_name='tempzakazgoods',
            name='availability_changed',
            field=models.BooleanField(default=False, help_text='\u0423\u0441\u0442\u043e\u043d\u0430\u0432\u043b\u0438\u0432\u0430\u0435\u0442\u0441\u044f \u0432 "True", \u0435\u0441\u043b\u0438 \u043d\u0430\u043b\u0438\u0447\u0438\u0435 \u0442\u043e\u0432\u0430\u0440\u0430 \u0431\u044b\u043b\u043e \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u043e, \u0447\u0442\u043e\u0431\u044b \u043e\u0434\u0438\u043d \u0440\u0430\u0437 \u0443\u0432\u0435\u0434\u043e\u043c\u0438\u0442\u044c \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f \u043e\u0431 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u0438 \u043d\u0430\u043b\u0438\u0447\u0438\u044f \u0442\u043e\u0432\u0430\u0440\u0430', verbose_name='\u041d\u0430\u043b\u0438\u0447\u0438\u0435 \u0438\u0437\u043c\u0435\u043d\u0438\u043b\u043e\u0441\u044c'),
        ),
        migrations.AddField(
            model_name='tempzakazgoods',
            name='summ_changed',
            field=models.BooleanField(default=False, help_text='\u0423\u0441\u0442\u043e\u043d\u0430\u0432\u043b\u0438\u0432\u0430\u0435\u0442\u0441\u044f \u0432 "True", \u0435\u0441\u043b\u0438 \u0441\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c \u0442\u043e\u0432\u0430\u0440\u0430 \u0431\u044b\u043b\u0430 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0430, \u0447\u0442\u043e\u0431\u044b \u043e\u0434\u0438\u043d \u0440\u0430\u0437 \u0443\u0432\u0435\u0434\u043e\u043c\u0438\u0442\u044c \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f \u043e\u0431 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u0438 \u0441\u0443\u043c\u043c\u044b \u0437\u0430\u043a\u0430\u0437\u0430', verbose_name='\u0421\u0443\u043c\u043c\u0430 \u0438\u0437\u043c\u0435\u043d\u0438\u043b\u0430\u0441\u044c'),
        )
    ]
