# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-06-04 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0095_auto_20210601_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemphoto',
            name='item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Item', verbose_name='\u0432\u0435\u0441/\u0442\u0438\u043f \u0441 \u0446\u0435\u043d\u043e\u0439'),
        ),
    ]
