# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-07-06 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0097_auto_20210608_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='working_mode_end',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='working_mode_start',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='fri_end',
            field=models.TimeField(blank=True, null=True, verbose_name='\u041e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u0435 \u0440\u0430\u0431\u043e\u0447\u0435\u0433\u043e \u0434\u043d\u044f'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='fri_start',
            field=models.TimeField(blank=True, null=True, verbose_name='\u041d\u0430\u0447\u0430\u043b\u043e \u0440\u0430\u0431\u043e\u0447\u0435\u0433\u043e \u0434\u043d\u044f'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='mon_end',
            field=models.TimeField(blank=True, null=True, verbose_name='\u041e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u0435 \u0440\u0430\u0431\u043e\u0447\u0435\u0433\u043e \u0434\u043d\u044f'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='mon_start',
            field=models.TimeField(blank=True, null=True, verbose_name='\u041d\u0430\u0447\u0430\u043b\u043e \u0440\u0430\u0431\u043e\u0447\u0435\u0433\u043e \u0434\u043d\u044f'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='sat_end',
            field=models.TimeField(blank=True, null=True, verbose_name='\u041e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u0435 \u0440\u0430\u0431\u043e\u0447\u0435\u0433\u043e \u0434\u043d\u044f'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='sat_start',
            field=models.TimeField(blank=True, null=True, verbose_name='\u041d\u0430\u0447\u0430\u043b\u043e \u0440\u0430\u0431\u043e\u0447\u0435\u0433\u043e \u0434\u043d\u044f'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='sun_end',
            field=models.TimeField(blank=True, null=True, verbose_name='\u041e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u0435 \u0440\u0430\u0431\u043e\u0447\u0435\u0433\u043e \u0434\u043d\u044f'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='sun_start',
            field=models.TimeField(blank=True, null=True, verbose_name='\u041d\u0430\u0447\u0430\u043b\u043e \u0440\u0430\u0431\u043e\u0447\u0435\u0433\u043e \u0434\u043d\u044f'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='thurs_end',
            field=models.TimeField(blank=True, null=True, verbose_name='\u041e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u0435 \u0440\u0430\u0431\u043e\u0447\u0435\u0433\u043e \u0434\u043d\u044f'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='thurs_start',
            field=models.TimeField(blank=True, null=True, verbose_name='\u041d\u0430\u0447\u0430\u043b\u043e \u0440\u0430\u0431\u043e\u0447\u0435\u0433\u043e \u0434\u043d\u044f'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='tues_end',
            field=models.TimeField(blank=True, null=True, verbose_name='\u041e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u0435 \u0440\u0430\u0431\u043e\u0447\u0435\u0433\u043e \u0434\u043d\u044f'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='tues_start',
            field=models.TimeField(blank=True, null=True, verbose_name='\u041d\u0430\u0447\u0430\u043b\u043e \u0440\u0430\u0431\u043e\u0447\u0435\u0433\u043e \u0434\u043d\u044f'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='wed_end',
            field=models.TimeField(blank=True, null=True, verbose_name='\u041e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u0435 \u0440\u0430\u0431\u043e\u0447\u0435\u0433\u043e \u0434\u043d\u044f'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='wed_start',
            field=models.TimeField(blank=True, null=True, verbose_name='\u041d\u0430\u0447\u0430\u043b\u043e \u0440\u0430\u0431\u043e\u0447\u0435\u0433\u043e \u0434\u043d\u044f'),
        )
    ]
