# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-07-06 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0098_auto_20210706_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='thurs_end',
            new_name='thu_end',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='thurs_start',
            new_name='thu_start',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='tues_end',
            new_name='tue_end',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='tues_start',
            new_name='tue_start',
        )
    ]
