# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-07-09 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0099_auto_20210706_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketOfGoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430 \u0437\u0430\u043f\u0443\u0441\u043a\u0430')),
                ('date_ended', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430 \u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u044f')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Item', verbose_name='\u0422\u043e\u0432\u0430\u0440')),
            ],
            options={
                'ordering': ['date_ended', 'date_started'],
                'verbose_name': '\u0422\u043e\u0432\u0430\u0440 \u0434\u043b\u044f \u043a\u043e\u0440\u0437\u0438\u043d\u044b \u0434\u043e\u0431\u0440\u0430',
                'verbose_name_plural': '\u0422\u043e\u0432\u0430\u0440\u044b \u0434\u043b\u044f \u043a\u043e\u0440\u0437\u0438\u043d\u044b \u0434\u043e\u0431\u0440\u0430',
            },
        ),
        migrations.AddField(
            model_name='tempzakazgoods',
            name='basket_of_good',
            field=models.BooleanField(default=False, verbose_name='\u041a\u043e\u0440\u0437\u0438\u043d\u0430 \u0434\u043e\u0431\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='zakazgoods',
            name='basket_of_good',
            field=models.BooleanField(default=False, verbose_name='\u041a\u043e\u0440\u0437\u0438\u043d\u0430 \u0434\u043e\u0431\u0440\u0430'),
        )
    ]
