# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-08-23 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0100_auto_20210709_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='title_search',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 (\u0434\u043b\u044f \u043f\u043e\u0438\u0441\u043a\u0430)'),
        )
    ]
