# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-10-21 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0101_auto_20210823_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZakazGoodsBaskedOfGoodsProxy',
            fields=[
            ],
            options={
                'verbose_name': '\u0442\u043e\u0432\u0430\u0440 \u0438\u0437 \u043a\u043e\u0440\u0437\u0438\u043d\u044b \u0434\u043e\u0431\u0440\u0430',
                'proxy': True,
                'verbose_name_plural': '\u0422\u043e\u0432\u0430\u0440\u044b \u0438\u0437 \u043a\u043e\u0440\u0437\u0438\u043d\u044b \u0434\u043e\u0431\u0440\u0430',
            },
            bases=('catalog.zakazgoods',),
        ),
        migrations.AddField(
            model_name='zakazgoods',
            name='is_shipped',
            field=models.BooleanField(default=False, verbose_name='\u041e\u0442\u0433\u0440\u0443\u0436\u0435\u043d'),
        ),
    ]
