# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2022-03-01 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0102_auto_20211021_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='is_refund',
            field=models.BooleanField(default=False, verbose_name='\u0412\u043e\u0437\u0432\u0440\u0430\u0442 \u043f\u0440\u0438\u0445\u043e\u0434\u0430'),
        ),
    ]
