# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2022-05-28 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0103_auto_20220301_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupfilter',
            name='is_tag',
            field=models.BooleanField(default=False, verbose_name='\u042d\u0442\u0430 \u0433\u0440\u0443\u043f\u043f\u0430 \u0442\u0435\u0433\u0438'),
        ),
        migrations.AlterField(
            model_name='tempzakazgoods',
            name='availability_changed',
            field=models.BooleanField(default=False, help_text='\u0423\u0441\u0442\u043e\u043d\u0430\u0432\u043b\u0438\u0432\u0430\u0435\u0442\u0441\u044f \u0432 "True", \u0435\u0441\u043b\u0438 \u043d\u0430\u043b\u0438\u0447\u0438\u0435 \u0442\u043e\u0432\u0430\u0440\u0430 \u0431\u044b\u043b\u043e \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u043e, \u0447\u0442\u043e\u0431\u044b \u043e\u0434\u0438\u043d \u0440\u0430\u0437 \u0443\u0432\u0435\u0434\u043e\u043c\u0438\u0442\u044c \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f \u043e\u0431 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u0438 \u043d\u0430\u043b\u0438\u0447\u0438\u044f \u0442\u043e\u0432\u0430\u0440\u0430', verbose_name='\u041d\u0430\u043b\u0438\u0447\u0438\u0435 \u0438\u0437\u043c\u0435\u043d\u0438\u043b\u043e\u0441\u044c (\u043f\u043e\u043b\u0435 \u043d\u0430 \u0434\u0430\u043d\u043d\u044b\u0439 \u043c\u043e\u043c\u0435\u043d\u0442 \u043d\u0435 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0435\u0442\u0441\u044f)'),
        ),
    ]
