# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2023-06-04 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0106_auto_20230604_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='slider_link',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u044c\u043d\u0430\u044f \u0441\u0441\u044b\u043b\u043a\u0430 \u0432 \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0435'),
        ),
    ]
