# Generated by Django 4.2.11 on 2024-03-25 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20210608_1537'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0107_producer_slider_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentitem',
            name='status',
            field=models.CharField(choices=[('1', 'ожидание модерации'), ('2', 'опубликованный'), ('3', 'отклоненный')], default='1', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='name',
            field=models.CharField(default='Name', max_length=256, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='deckitem',
            name='type',
            field=models.CharField(blank=True, choices=[('wet', 'Влажный'), ('dry', 'Сухой'), ('additional', 'Добавка')], max_length=16, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expensetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.expensetype', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='insidezakaz',
            name='courier',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__permissions__codename': 'courier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Курьер'),
        ),
        migrations.AlterField(
            model_name='insidezakaz',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__permissions__codename': 'manager', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_insidezakaz_set', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='insidezakaz',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.warehouse', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='insidezakazgoods',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.new', verbose_name='Акция'),
        ),
        migrations.AlterField(
            model_name='insidezakazstatuslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),
        ),
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.TextField(default='', verbose_name='Штрихкод'),
        ),
        migrations.AlterField(
            model_name='logingcourierfinish',
            name='courier',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__permissions__codename': 'courier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_logcourierfinish_set', to=settings.AUTH_USER_MODEL, verbose_name='Курьер'),
        ),
        migrations.AlterField(
            model_name='movementofgoods',
            name='courier',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__permissions__codename': 'courier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Курьер'),
        ),
        migrations.AlterField(
            model_name='movementstatuslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),
        ),
        migrations.AlterField(
            model_name='outsidezakaz',
            name='courier',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__permissions__codename': 'courier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_outsidezakaz_set', to=settings.AUTH_USER_MODEL, verbose_name='Курьер'),
        ),
        migrations.AlterField(
            model_name='outsidezakazstatuslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='margin',
            field=models.FloatField(default='1.3', verbose_name='Наценка'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='margin_heavy',
            field=models.FloatField(default='1.3', verbose_name='Наценка тяжелых'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='reservelog',
            name='inside_zakaz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.insidezakaz', verbose_name='Заказ поставщика'),
        ),
        migrations.AlterField(
            model_name='reservelog',
            name='movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.movementofgoods', verbose_name='Перемещение'),
        ),
        migrations.AlterField(
            model_name='reservelog',
            name='zakaz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.zakaz', verbose_name='Заказ клиента'),
        ),
        migrations.AlterField(
            model_name='tempzakazgoods',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.new', verbose_name='Акция'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='default_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель по-умолчанию'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='cashier',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__id': '3'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashier_zakaz_set', to=settings.AUTH_USER_MODEL, verbose_name='Кассир'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='courier',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__permissions__codename': 'courier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_zakaz_set', to=settings.AUTH_USER_MODEL, verbose_name='Курьер'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__permissions__codename': 'manager', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_zakaz_set', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='pickup_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_warehouse', to='catalog.warehouse', verbose_name='Пункт выдачи(при самовывозе)'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='warehouse',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse', to='catalog.warehouse', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='zakazbonus',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.item', verbose_name='Подарок'),
        ),
        migrations.AlterField(
            model_name='zakazgoods',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.new', verbose_name='Акция'),
        ),
        migrations.AlterField(
            model_name='zakazstatuslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),
        ),
    ]
