# Generated by Django 3.2.25 on 2024-05-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0109_auto_20240506_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deckitem',
            name='type',
            field=models.CharField(blank=True, choices=[('wet', 'Влажный'), ('dry', 'Сухой'), ('additional', 'Добавка')], max_length=16, null=True, verbose_name='Тип'),
        ),
    ]
