# Generated by Django 3.2.25 on 2024-05-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0110_alter_deckitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deckitem',
            name='sale',
            field=models.FloatField(blank=True, null=True, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='deckitem',
            name='type',
            field=models.CharField(blank=True, choices=[('additional', 'Добавка'), ('wet', 'Влажный'), ('dry', 'Сухой')], max_length=16, null=True, verbose_name='Тип'),
        ),
    ]
