# Generated by Django 3.2.25 on 2024-05-10 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0112_alter_deckitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='warehouse',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.warehouse', verbose_name='К складу'),
        ),
        migrations.AlterField(
            model_name='deckitem',
            name='type',
            field=models.CharField(blank=True, choices=[('wet', 'Влажный'), ('dry', 'Сухой'), ('additional', 'Добавка')], max_length=16, null=True, verbose_name='Тип'),
        ),
    ]
