# Generated by Django 3.2.25 on 2024-05-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0113_auto_20240510_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='item',
            name='warehouse',
            field=models.ManyToManyField(to='catalog.WareHouse'),
        ),
    ]
