# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-07 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import sberbank.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0053_auto_20200507_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankLog',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_id', models.UUIDField(null=True)),
                ('bank_id', models.UUIDField(null=True)),
                ('request_type', models.CharField(choices=[(0, b'CREATE'), (1, b'CALLBACK'), (2, b'CHECK_STATUS')], max_length=1)),
                ('response_json', jsonfield.fields.JSONField(blank=True, null=True)),
                ('response_text', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('bank_id', models.UUIDField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=65)),
                ('error_code', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, b'CREATED'), (1, b'PENDING'), (2, b'SUCCEEDED'), (3, b'FAILED')], default=sberbank.models.Status(0))),
                ('details', jsonfield.fields.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('payservice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_zakaz', to='catalog.Zakaz', verbose_name='\u0417\u0430\u043a\u0430\u0437')),
            ],
        ),
    ]
