# Generated by Django 4.2.11 on 2024-03-25 13:18

from django.db import migrations, models
import sberbank.models


class Migration(migrations.Migration):

    dependencies = [
        ('sberbank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banklog',
            name='request_type',
            field=models.CharField(choices=[(0, 'CREATE'), (1, 'CALLBACK'), (2, 'CHECK_STATUS')], max_length=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'CREATED'), (1, 'PENDING'), (2, 'SUCCEEDED'), (3, 'FAILED')], default=sberbank.models.Status['CREATED']),
        ),
    ]
